### ISSUE TITLE
Support WebFlux SpringBoot projects when it comes to generate probes for actuators

### ISSUE THREAD

**Issue by nightswimmings** [eclipse-jkube/jkube#1125]
SpringBootHealthCheckEnricher uses servlet properties exclusively in order to generate probes

```
prefix = springBootProperties.getProperty(propertyHelper.getServerContextPathPropertyKey(), "");
prefix += springBootProperties.getProperty(propertyHelper.getServletPathPropertyKey(), "");
prefix += springBootProperties.getProperty(propertyHelper.getManagementContextPathPropertyKey(), "");
```

When the service is reactive (webflux) the equivalent counterpart property is spring.webflux.base-path

**Comment by rohanKanojia** [comment]
Thanks for reporting this issue. Would it be possible for you to contribute a PR for this?

**Comment by nightswimmings** [comment]
I'll try to find a moment during this week, I guess it requires testing, because otherwise its a 10 min change

**Comment by rohanKanojia** [comment]
I see [Spring Boot Configuration](https://docs.spring.io/spring-boot/appendix/application-properties/index.html) doc page and I only see `spring.webflux.base-path` having collisions with `server.servlet.context-path`.

There are other Webflux properties as well but they don't collide with existing properties used in SpringBootConfiguration
