### ISSUE TITLE
Remove storageClass related fields from VolumePermissionEnricher

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#1989]
### Component

JKube Kit

### Description

Related to https://github.com/eclipse/jkube/issues/1179 https://github.com/eclipse/jkube/pull/1928

:construction: Requires #1928 to get merged and released so that we can remove deprecated fields in this release :construction: 

VolumePermissionEnricher seems to be doing more than just changing permission of mounted volume. It also seems to be setting storageClass in PVC.

We moved storageClass related logic in #1928 into PersistentVolumeClaimStorageClassEnricher. However, there are these configuration fields still present in VolumePermissionEnricher:

https://github.com/eclipse/jkube/blob/751a8aacd83de57cf05256a0c7e493926a752652/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L63-L64

They've been marked as `@Deprecated` for now but we need to remove this in future.

This is just a reminder task to remove these configuration fields and related methods from VolumePermissionEnricher in future.

### Expected Behavior
VolumePermissionEnricher shouldn't have any configuration fields related to storageClass 

### Acceptance Criteria
- [ ] `defaultStorageClass` and `useStorageClassAnnotation` have been removed from VolumePermissionEnricher.Config

**Comment by rohanKanojia** [comment]
Sorry, I created this task for future reference. /it's not applicable at the moment

> Requires https://github.com/eclipse/jkube/pull/1928 to get merged and released so that we can remove deprecated fields in this release

Shall I create some other issue for you to pick up?

**Comment by omjikush09** [comment]
Hi,@rohanKanojia  It would be great if you could create some new issues; I would love to contribute.  
Thanks for it.

**Comment by omjikush09** [comment]
Hi, @rohanKanojia and @sunix  can I work on this now?

**Comment by rohanKanojia** [comment]
@omjikush09 : Sorry https://github.com/eclipse/jkube/pull/1928 still isn't merged yet. Shall I create some other issue for you to pick up?

**Comment by omjikush09** [comment]
Yup that would be great. :smile:
