### ISSUE TITLE
Create a "status/need-triage" label to track issues that have not been reviewed

### ISSUE THREAD

**Issue by sunix** [eclipse-jkube/jkube#2139]
### Component

None

### Description
Like in Eclipse che, a bot is automatically adding the label https://github.com/eclipse/che/labels?q=triage

**Comment by sunix** [comment]
also to be addressed in fabric8 k8s client https://github.com/fabric8io/kubernetes-client/issues/5055

**Comment by gbraad** [comment]
@sunix Have you followed-up on this?
