### ISSUE TITLE
Remove ClusterAccess class

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2164]
### Component

JKube Kit

### Description

After #2163 / #2155 the `ClusterAccess` class is just a wrapper around the `ClusterConfiguration` class. We should remove `ClusterAccess` altogether.

**Comment by Devashishbasu** [comment]
please assign this issue to me

**Comment by manusa** [comment]
I don't think this is a good first issue, it requires refactoring at several levels.

**Comment by rohanKanojia** [comment]
I think @Devashishbasu has already contributed to jkube in https://github.com/jkubeio/jkube-images/pull/39 . 

@Devashishbasu : Have you started any work on this? if not, shall I unassign you from this issue. I can create some other issue for you if you want.

**Comment by Devashishbasu** [comment]
> I think @Devashishbasu has already contributed to jkube in [jkubeio/jkube-images#39](https://github.com/jkubeio/jkube-images/pull/39) .
> 
> @Devashishbasu : Have you started any work on this? if not, shall I unassign you from this issue. I can create some other issue for you if you want.

Hii @rohanKanojia ..yes please create some issues on which you think I can work on.

**Comment by rohanKanojia** [comment]
@Devashishbasu : I've created two good first issues. Could you please check if you can pick any of those?

**Comment by Devashishbasu** [comment]
> @Devashishbasu : I've created two good first issues. Could you please check if you can pick any of those?

Thankyou...I can do both please assign both to me
