### ISSUE TITLE
JKube generators should be able to provide opinionated BuildPackConfiguration

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2460]
### Component

None

### Description
Part of #439 

Currently, our generators provide opinionated ImageConfiguration by inspecting project configuration.

As a user building container image leveraging buildpacks, JKube generators should be able to create opinionated BuildPackConfiguration along with ImageConfiguration. This should be supported for frameworks that have buildpacks supported officially.

### Expected Behavior
As a user, when I build container image using buildpacks, I expect jkube generators to choose the appropriate buildpack builder image automatically. This should be applicable provided there is an officially supported buildpack available for a particular framework (spring-boot, quarkus)

### Acceptance Criteria
- [ ] JKube Generators should be able to configure BuildPackConfiguration aspects as per applicable frameworks

**Comment by manusa** [comment]
As discussed internally:

> Choosing the buildpacks strategy is just telling JKube to delegate everything to buildpacks. JKube is only responsible for picking up the image name and creating suitable resources.

> Maybe this can be more explicit in the docs. Stating that buildpacks strategy is a delegation and the user is completely responsible to provide a valid buildpacks configuration.

**Comment by rohanKanojia** [comment]
> Maybe this can be more explicit in the docs. Stating that buildpacks strategy is a delegation and the user is completely responsible to provide a valid buildpacks configuration.

We have updated the documentation addressing this aspect in #3069 . I think we can close this issue.
