### ISSUE TITLE
[US] Buildpacks unsupported Maven/Gradle goals/tasks

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2494]
## Description

Part of #439 

As a user, when I run an unsupported goal/task with the buildpacks strategy in my Maven/Gradle project I expect to receive a warning, so that I am aware that the goal/task is not yet supported.

**Comment by rohanKanojia** [comment]
We have made changes in these goals/tasks  to throw exception buildpacks in build strategy
- `k8sWatch` https://github.com/eclipse-jkube/jkube/pull/2835
- `k8sDebug` https://github.com/eclipse-jkube/jkube/pull/2957

I think the rest of the goals should be unaffected by buildpacks build strategy as their functionality does not depend on the behavior of packaged container image:
- `k8sResource` (deals with resource manifests)
- `k8sApply` (deals with applying resource manifest)
- `k8sUndeploy` (deals with deleting applied manifests)
- `k8sLog` (interacts with K8s to get logs)
- `remoteDev` (for exposing services)
- `helm` (generate helm charts from resource manifests)
- `helmPush` (push helm charts to helm/oci registries)
- `helmLint` (lint generated charts)
