### ISSUE TITLE
KubernetesBuildTaskTest.setUp The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2632]
### Description

The method [KubernetesBuildTaskTest.setUp](https://github.com/eclipse-jkube/jkube/blob/cd8f26525b524f295249d86419bd249b8398644e/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L59) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/cd8f26525b524f295249d86419bd249b8398644e/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L59

- [ ] should be changed to:

```java
  void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Adityaturkhade** [comment]
Can you please assign this issue to me?

**Comment by shree-crypto** [comment]
would love to contribute to it as my first contri @manusa

**Comment by manusa** [comment]
> would love to contribute to it as my first contri @manusa

Hi @shree-crypto, you've been assigned #2591

**Comment by AkashDeepSinghJassal** [comment]
Can you assign me this issue?

**Comment by AkashDeepSinghJassal** [comment]
This issue is already resolved in master branch
https://github.com/eclipse-jkube/jkube/blob/78e8631c9c101e52dc94f14fb97c16383396afc5/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L59

but still, there is unused import
https://github.com/eclipse-jkube/jkube/blob/cd8f26525b524f295249d86419bd249b8398644e/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L16

change the task description to remove unused import, or close the task @rohanKanojia

**Comment by rohanKanojia** [comment]
Please go ahead and create pull request to remove the unused import. 

I'll update the issue description
