### ISSUE TITLE
PortForwardServiceTest.setUp The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2749]
### Description

The method [PortForwardServiceTest.setUp](https://github.com/eclipse-jkube/jkube/blob/108f6ed341bbc4760b7e6b8497ea28004945fc58/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java#L54) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/108f6ed341bbc4760b7e6b8497ea28004945fc58/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java#L54

- [x] should be changed to:

```java
    void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by clarenced** [comment]
Hi, I can also help with this issue

**Comment by rohanKanojia** [comment]
@clarenced Hello, first-timers-only issue labels are created for people who are contributing for the first time. I think you should look into `good-first-issue`/`help-wanted` labels.

**Comment by sriharsha1296** [comment]
Hi, You can assign this to me. I haven't done any contribution before.

**Comment by lcardito** [comment]
Hey team! @manusa mind if I take this one as my first contribution? Sorry I jumped the gun a little and I already got a PR open 🥲 https://github.com/eclipse-jkube/jkube/pull/3331
