### ISSUE TITLE
KubernetesHelper : Replace call to `toArray()` with a pre-sized array argument with empty array

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2837]
### Component

JKube Kit

### Description

We seem to have code here that converts a List to an array:

https://github.com/eclipse/jkube/blob/b10c54f17d33974c80c1fc4a26ce6a44ef29dcf7/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java#L443

Sonar reports it as a code smell as the recommended usage is to use empty array instead:
```java
String[] valuesArray = values.toArray(new String[0]);
```

### Expected Behavior
The pre-sized array is replaced with an empty array

### Acceptance Criteria
- [x] Pre-sized array is replaced with an empty array
- [x] Project builds okay after running `mvn clean install`

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Sudarsan-Pradhan** [comment]
If this issue still not fixed can i contribute to it ?

**Comment by rohanKanojia** [comment]
@rschulm : Hello, are you still working on it?

**Comment by Teja-11** [comment]
If this is still not fixed, can i work on this?

**Comment by manusa** [comment]
Hi @rschulm, I'm unassigning this issue. Feel free to choose another or reapply for this one if no one else resolves it first.

**Comment by Sintivrousai** [comment]
Can i be assigned for the issue?
