### ISSUE TITLE
ValidationUtil : Replace String concatenation arguments with `StringBuilder.append()` call 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2840]
### Component

JKube Kit

### Description

We are using string concatenation within a String builder call:
https://github.com/eclipse/jkube/blob/b10c54f17d33974c80c1fc4a26ce6a44ef29dcf7/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java#L45

Sonar flags them as a code smell. We should refactor this code to use chained `.append` calls like this:
```java
builder.append(violation.getPropertyPath()).append(" ").append(violation.getMessage()).append(" on bean: ").append(leafBean);
```
### Expected Behavior
String concatenation is replaced with `.append` calls

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by s-mathavan** [comment]
I like to help you with this

**Comment by Prab-27** [comment]
@s-mathavan is this issue still open? I am a first time contributor and want to contribute

**Comment by rohanKanojia** [comment]
@Prab-27 : There is a pull request open #2846 but it's not complying with Eclipse Contributor Legal Requirements.

**Comment by ngthhu** [comment]
Can I work on this?

**Comment by rohanKanojia** [comment]
@ngthhu : Are you still working on this issue? I see you've made some changes related to this issue.

**Comment by AndrewJCate** [comment]
I can tackle this if it's still open.
