### ISSUE TITLE
Provide a way to set labels on images defined by Generators

### ISSUE THREAD

**Issue by davidecavestro** [eclipse-jkube/jkube#2885]
### Component

Kubernetes Maven Plugin

### Is your enhancement related to a problem? Please describe

I miss a way to set labels on the container image when I build it through _generators_ (instead of the _images_ config). I use the spring-boot generator, but I suppose the issue is common to others.

### Describe the solution you'd like

I'd like to add a labels entry to the generator config, such as
```pom.xml
...
<generator>
  <config>
    <spring-boot>
      <color>always</color>
      <from>...</from>
      <labels>foo=abc,bar=123</labels><!-- with a CSV or nested elems -->
    </spring-boot>
  </config>
</generator>
...
```
Probably a comma separated list of values would resemble what already happens for _jkube.generator.tags_.

### Describe alternatives you've considered

Using _images_ tag or _dockerfile_ I would loose the support for automatic detection of layered jars

### Additional context

Discussed at https://github.com/eclipse/jkube/discussions/2884

**Comment by rohanKanojia** [comment]
@davidecavestro : Would it be possible for you to work on this? I'm happy to provide you code pointers if interested.

**Comment by davidecavestro** [comment]
This way it works
![image](https://github.com/eclipse/jkube/assets/447917/9bcde88d-7fb2-4c2f-b60b-32d5948b7695)
but I am wondering what's the best way to support dynamic values for the labels
i.e. setting the value from a property or an env variable

**Comment by rohanKanojia** [comment]
> i.e. setting the value from a property or an env variable

Not 100% sure how to do it. Maybe adding a map/property configuration option in Mojos/ Gradle tasks can help achieve this. But then maybe we would need to align that configuration option with both generators (zero configuration) and explicit image configuration.

**Comment by davidecavestro** [comment]
I see, not sure if filter support could help someway... should investigate.
Another aspect to refine would be the escaping of commas and equals chars.

**Comment by manusa** [comment]
> i.e. setting the value from a property or an env variable

I think the easiest way right now would be to control that from Maven by computing the value as a property first:

```xml
<properties>
  <prop>pre</prop>
  <jkube.generator.labels>${prop}-${env.ENV_PROP}</jkube.generator.labels>
  <!-- ... -->
</properties>
```

> Another aspect to refine would be the escaping of commas and equals chars.

Not sure of how we're doing that for tags now, but both features should follow the same approach for sanitizing inputs.

**Comment by davidecavestro** [comment]
> the easiest way right now would be to control that from Maven by computing the value as a property first

so I see the interpolation is done by maven both defining a property and directly using expressions such as `<labels>${my.prop}=${env.GIT_COMMIT}</labels>`
I expect the same would stand for gradle, but I've not checked

> Not sure of how we're doing that for tags now, but both features should follow the same approach for sanitizing inputs

I see no sanitization for tags at [addTagsFromConfig](https://github.com/eclipse/jkube/blob/579e7df2005531a8f6ba86e037ea975385d807a9/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L234C1-L242C6)

OTOH [EnvUtils.splitOnSpaceWithEscape](https://github.com/eclipse/jkube/blob/579e7df2005531a8f6ba86e037ea975385d807a9/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java#L210) could be replicated into separate methods to extract lists (tags use case) and maps (labels use case) supporting both comma cahrs (entries separators) and equal chars (key/value separators).
Both chars could be escaped this way.

That said, it may seem too complicated as it reduce code readability (on my own I don't have a real-world use case for escaping yet).

**Comment by manusa** [comment]
> so I see the interpolation is done by maven both defining a property and directly using expressions such as <labels>${my.prop}=${env.GIT_COMMIT}</labels>

Yes, that should work too.

> I expect the same would stand for gradle, but I've not checked

For Gradle it should be done differently, but would be achievable too.

What I mean, in general, is that for dynamic values instead of reinventing the wheel downstream, it's better to leverage the tools that the build system offers.

> That said, it may seem too complicated, as it reduces code readability increasing complexity.

Maybe in this case (it seems to be far more complex than for tags) it's better to try and see what Docker or other tools are doing to ensure a consistent behavior.

https://docs.docker.com/config/labels-custom-metadata/#label-keys-and-values

**Comment by davidecavestro** [comment]
Please note that the complexity of parsING and escaping separators is clearly related to the choice of setting labels via a CSV.
IMHO apart from the escape of separators, there's no strong need of specific sanitization (probably enforced by underlying layers if really needed).

Also consider that in case we opt instead for shaping labels with nested config elements, we would end up with something simpler (but this approach would differ from _tags_ one).

**Comment by manusa** [comment]
OK, note that we would likely want to support the label setting via configuration elements (regardless of the nesting choice), but also through the use of a property `jkube.generator.labels`. That's why I was mostly concerned about the parsing and its complexity.

**Comment by davidecavestro** [comment]
> also through the use of a property `jkube.generator.labels`. That's why I was mostly concerned about the parsing and its complexity

makes sense
so given the mandate to support encoding a map into a one-liner - possibly passed from CLI - a certain degree of complexity for parsing seems acceptable to me

**Comment by davidecavestro** [comment]
What about json?

**Comment by davidecavestro** [comment]
After some issues with GPG signature (ssh keys were not an option on this network)
I sketched https://github.com/eclipse-jkube/jkube/pull/2956

I saw some issues on tests and licenses check: if they are not false positives I can look at them
