### ISSUE TITLE
BaseGeneratorTest Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2921]
### Description

The class [BaseGeneratorTest](https://github.com/eclipse-jkube/jkube/blob/5931629ea51e061bd852cd75d8561a547bdf9711/jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/5931629ea51e061bd852cd75d8561a547bdf9711/jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java#L16-L19

- [ ] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by tejachalla123** [comment]
can i work on this?

**Comment by manusa** [comment]
HI @tejachalla123, are you still working on this? it's been over a month now, we usually give 2 weeks max to complete an issue of this kind.

**Comment by CroWzblooD** [comment]
can u assign me I would like to work on this.

**Comment by CroWzblooD** [comment]
![Screenshot 2024-06-21 111918](https://github.com/eclipse-jkube/jkube/assets/91479132/21280d8e-f39b-4d31-bb6b-001722d8a566)
i think the unused imports are already removed from BaseGeneratorTest class 
pls let me know... Bec its my first time to contribute might be I'm wrong pls correct me...
