### ISSUE TITLE
HelmService Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2923]
### Description

The class [HelmService](https://github.com/eclipse-jkube/jkube/blob/fddd604457c98a197bd8b2f3cbb3167dde2a9b3d/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/fddd604457c98a197bd8b2f3cbb3167dde2a9b3d/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L19

- [ ] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by suhassk-hash** [comment]
Please assign this to me

**Comment by manoj-r** [comment]
I'd like to fix this. Can you please assign this to me?

**Comment by manoj-r** [comment]
@rohanKanojia Looks like this was already fixed by @manusa. This issue can be closed. https://github.com/eclipse-jkube/jkube/blob/master/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
