### ISSUE TITLE
HelmMojo : Remove redundant method identical to super method

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2929]
### Component

Kubernetes Maven Plugin

### Description

I think this was probably introduced due to this refactor https://github.com/eclipse/jkube/pull/2714

There is a method present in HelmMojo that is overriding a method from its superclass: 

https://github.com/eclipse-jkube/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java#L74-L77

However, if we look at the method in AbstractHelmMethod, it is identical to one in HelmMojo.
https://github.com/eclipse-jkube/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractHelmMojo.java#L55-L57

If HelmMojo's `@Override` method is not doing anything different, there is no point keeping it. 
### Expected Behavior
HelmMojo's redundant method identical to its super method is removed.

### Acceptance Criteria
- [x] redundant method is removed from HelmMojo
- [x] Project compiles cleanly after running `mvn clean install`

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by elizasorber** [comment]
Hi @rohanKanojia ! I'm a college student wanting to make my first contribution. Can I work on this issue?

**Comment by rohanKanojia** [comment]
@elizasorber Sorry this issue is created for people who have already contributed to the project before. Once you've made your first contribution, you can pick it.

We have a separate label first-timers-only for issues created for newcomers. Could you please take a look at those?

**Comment by elizasorber** [comment]
Thank you! I will check that out.

**Comment by Teja-11** [comment]
Hi, 

can i work on this?

**Comment by rohit-satya** [comment]
@rohanKanojia Please review above PR
