### ISSUE TITLE
`HelmConfig.HelmType` may use lombok `@Getter`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2930]
### Component

JKube Kit

### Description

This class has explicit getters that can easily be replaced by using [Lombok's `@Getter` ](https://projectlombok.org/features/GetterSetter)annotation.

https://github.com/eclipse/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java#L93-L115

### Expected Behavior
Getter methods are removed and `@Getter` annotation is used

### Acceptance Criteria
- [ ] `@Getter` annotation is used in place of handwritten getters
- [ ] Project compiles cleanly after running `mvn clean install`

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by akshay11agrawal** [comment]
@rohanKanojia Interested in picking this issue, let me know if I can work on this
