### ISSUE TITLE
WildflJarGenerator : Define and throw a dedicated exception instead of using a generic one.

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2931]
### Component

JKube Kit

### Description

We're throwing a RuntimeException here in WildflyJarGenerator in case a directory does not exist:

https://github.com/eclipse/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java#L92-L93

Sonar reports this as a code smell. We had introduced a generic JKubeException class for exception handling like this. We can probably use JKubeException here instead of generic `RuntimeException`

https://github.com/eclipse/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeException.java#L16-L20

### Expected Behavior
Use JKubeException instead of RuntimeException

### Acceptance Criteria
- [ ] JKubeException is used in place of RuntimeException
- [ ]  Project compiles cleanly after running `mvn clean install`

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by mgurrie** [comment]
Can I be assigned this task? @rohanKanojia
