### ISSUE TITLE
Improve our CONTRIBUTING guide from a newcomer perspective

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2961]
### Component

None

### Description
Our CONTRIBUTING guide needs to be improved so that newcomers get a better idea of what to do and how to get started after reading it. In my opinion, this task can only be done by someone new to the project. At the moment, I see these issues:

- There is no information about which issues are suitable for newcomers. We have `first-timers-only` labeled issues for people contributing for the first time and `help wanted` labeled issues for contributors who have gone past their first contributions.
- There is no information about how to build the project and use the local build in some quickstart. This includes Running `mvn clean install -DskipTests` and pointing any quickstart to `SNAPSHOT` version .
- There is no information about how to debug plugin, using `mvnDebug` for maven and `gradle -Dorg.gradle.debug=true` on Gradle while debugging Kubernetes/OpenShift plugins needs to be specified.
- Many contributors are using Windows and face https://github.com/eclipse-jkube/jkube/issues/1338 , it needs to be specified in CONTRIBUTING guide to use `-DskipTests` while building on Windows

Here is a better example of CONTRIBUTING guide:
- https://www.libreoffice.org/community/developers/
- https://wiki.documentfoundation.org/Development/EasyHacks
- https://wiki.documentfoundation.org/Development

The source for CONTRIBUTING guide is located here: https://github.com/eclipse-jkube/jkube-website/blob/main/src/content/contributing/index.mdx

### Expected Behavior
The contributing guide is improved for newcomers

### Acceptance Criteria
- [ ] Contributing guide is improved and abovementioned points are added

**Comment by manusa** [comment]
Closed by https://github.com/eclipse-jkube/jkube-website/pull/89
