### ISSUE TITLE
OCIRegistryEndpoint Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2963]
### Description

The class [OCIRegistryEndpoint](https://github.com/eclipse-jkube/jkube/blob/0f530e0a6340dcb3dbc3b5ea3c4af40516dd1a17/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryEndpoint.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/0f530e0a6340dcb3dbc3b5ea3c4af40516dd1a17/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryEndpoint.java#L25

- [ ] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Jeevananthammoorthy** [comment]
@manusa  Interested to contribute in this issue, Kindly assign. Thanks.

**Comment by Jeevananthammoorthy** [comment]
@manusa @rohanKanojia  Kindly find the PR link https://github.com/eclipse-jkube/jkube/pull/2992
