### ISSUE TITLE
OCIRegistryInterceptorTest Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2964]
### Description

The class [OCIRegistryInterceptorTest](https://github.com/eclipse-jkube/jkube/blob/3b8a73d0112065abebc869573fbca2a6a6394f8f/jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptorTest.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/3b8a73d0112065abebc869573fbca2a6a6394f8f/jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptorTest.java#L16

- [x] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by kushagrasinha123ks** [comment]
I would like to work on this issue, if its available assign me.

**Comment by manusa** [comment]
Hi @kushagrasinha123ks, you've already been assigned #2966 and contributed a fix.
You can now proceed to those good first issues that are **not** tagged with first-timers-only.

**Comment by arman-yekkehkhani** [comment]
Hi! I am interested in working on this issue and pushing my first contribution. Could you please assign it to me?
