### ISSUE TITLE
Bump Buildpack `pack` version to latest available version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2969]
### Component

JKube Kit

### Description

:warning: This issue requires testing changes on Docker/Minikube

Ever since we added support for [Cloud Native BuildPacks](https://buildpacks.io/), we haven't updated buildpack version.
https://github.com/eclipse-jkube/jkube/blob/d9d630b453093efd827914ce71593117c0343569/jkube-kit/parent/pom.xml#L130

We should update it to the latest available version see [buildpack releases page](https://github.com/buildpacks/pack/releases) .

Once you've updated the version, you would also need to check whether `buildpacks` build strategy is working after the version upgrade. You would need to follow these steps : 

1. Make sure you have access to [Docker Daemon](https://docs.docker.com/config/daemon/start/)
2. Build Project `mvn clean install -DskipTests`
3. Go to some quickstart and change the `jkube.version` property to development version `1.17-SNAPSHOT`
4. Run `k8s:build` goal with buildpacks build strategy, If you would do it in `quickstarts/maven/spring-boot`, it would look like this:
```
$  mvn k8s:build -Djkube.build.strategy=buildpacks -Djkube.version=1.17-SNAPSHOT -Pkubernetes
```

### Expected Behavior
Pack version is updated to latest version.

### Acceptance Criteria
- [ ] `k8s:build` should work with new updated pack version
- [ ] Project builds successfully after running `mvn clean install`

**Comment by Jeevananthammoorthy** [comment]
@rohanKanojia  I have completed my first-timer PR, Could you assign this to me. I can work on it.

**Comment by Jeevananthammoorthy** [comment]
@rohanKanojia  Facing difficulty setting up docker in-local, as my windows version and wsl version is not compatible. Kindly unassign this issue from my name. Will go over other items and raise a new request.

**Comment by rohanKanojia** [comment]
@Jeevananthammoorthy : Have you tried setting up Podman on your machine? Not sure if you'll face the same problem for podman as well.

**Comment by rohanKanojia** [comment]
@MukarramHaq : Do you have docker set up on your machine? This issue might require testing a functionality on Docker after making changes.

**Comment by MukarramHaq** [comment]
Yes, I have docker setup on my machine. :)

I apologize for the delayed response.

**Comment by rohanKanojia** [comment]
@MukarramHaq : polite ping, are you still working on this issue?

**Comment by MukarramHaq** [comment]
Yes, I am. My laptop broke down so I had to order a new one. It will be delivered today or tomorrow and I can then start working on it i apologise for the delay
