### ISSUE TITLE
GoTimeUtilTest : Remove call to `Optional.get()` without `isPresent()` check 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2970]
### Component

JKube Kit

### Description
In GoTimeUtilTest, we're directly calling `Optional.get()` without checking whether there is any element present in the Optional, this might cause `NoSuchElementException` :

https://github.com/eclipse-jkube/jkube/blob/d9d630b453093efd827914ce71593117c0343569/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java#L32-L36

We should check whether `Optional.isPresent()` returns true, then only fetch the value. We can rely on [AssertJ](https://assertj.github.io/doc/#assertj-core-quick-start)'s builtin `isPresent()` and `contains(..)` DSL methods to verify these things for us.

### Expected Behavior
`.isPresent()` is added before directly checking value inside Optional

### Acceptance Criteria
- [x] GoTimeUtilTest is refactored to not directly call `Optional.get()`
- [x] GoTimeUtilTest is passing after making these changes

**Comment by kushagrasinha123ks** [comment]
i would like to work on this issue, if available assign me.

**Comment by rohanKanojia** [comment]
@kushagrasinha123ks Hello, `help wanted` issues are created for contributors who have already contributed to the project. I can see that you haven’t contributed to the project before.

Even if you are quite skilled, please consider doing one little ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issue to get used to the process. After that, you are invited to move on up to the more difficult tasks, leaving some of the easy tasks to others so they can get involved and achieve change themselves.  

Maybe you should start with issues created for first timers [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only)

**Comment by kushagrasinha123ks** [comment]
Reply: I have successfully contributed to one (first-timers-only) issue, which is merged for the ticket whose [link ](https://github.com/eclipse-jkube/jkube/pull/2977)i have provided below for reference. Even if that's not eligible, i'll stick to first-timers-only.

**Comment by kushagrasinha123ks** [comment]
I would request you to take a look on the last pull request, i have removed all the errors and it passed all the necessary checks.
