### ISSUE TITLE
ApplyService : Iteration can be replaced with bulk `Collection.addAll()` call 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2971]
### Component

JKube Kit

### Description
We have this code in ApplyService where we're iterating over a List and manually adding each element one by one: 

https://github.com/eclipse-jkube/jkube/blob/d9d630b453093efd827914ce71593117c0343569/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java#L571-L573

We can use [java.util.List.addAll](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#addAll-java.util.Collection-) method here to make this a one-liner instead.

### Expected Behavior
for loop is replaced with `addAll`

### Acceptance Criteria
- [x] `for` loop is replaced with list.addAll call
- [x] project compiles cleanly after running `mvn clean install`

**Comment by rohit-satya** [comment]
@rohanKanojia Please assign this issue to me
