### ISSUE TITLE
Use Lombok annotations in `org.eclipse.jkube.kit.config.resource.ConfigMap` class 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2972]
### Component

JKube Kit

### Description
We have this ConfigMap configuration class which is having handwritten getters and setters:

https://github.com/eclipse-jkube/jkube/blob/d9d630b453093efd827914ce71593117c0343569/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ConfigMap.java#L19-L39

These could easily be replaced by Lombok's `@Getter` and `@Setter` annotations

### Expected Behavior
Getters and setters are replaced with annotations provided by Lombok

### Acceptance Criteria
- [ ] Hand written getters and setters are removed
- [ ] Lombok annotations `@Getter`/`@Setter` are added to class
- [ ] Project compiles cleanly after running `mvn clean install`

**Comment by MukarramHaq** [comment]
Hello, I would like to work on this. Can you assign this to me?

**Comment by rohanKanojia** [comment]
@MukarramHaq Hello, `help wanted` issues are created for contributors who have already contributed to the project. I can see that you haven’t contributed to the project before. Maybe you should start with issues created for first timers [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only)

**Comment by MukarramHaq** [comment]
@rohanKanojia Oh, gotcha. Thank you for the tip! I actually knew how to do this so I thought I might ask. Thank you tho!

**Comment by manusa** [comment]
> @rohanKanojia Oh, gotcha. Thank you for the tip! I actually knew how to do this so I thought I might ask. Thank you tho!

That's fine, please complete one of the other issues first so that we ensure you have a valid ECA signature and that you're able to complete the our pull-request workflow. Then, you can certainly complete this issue. Thanks!

**Comment by rohanKanojia** [comment]
@MukarramHaq : Yes, you can also work on this one.

Even if you are quite skilled, please consider doing one little ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issue to get used to the process. After that, you are invited to move on up to the more difficult tasks, leaving some of the easy tasks to others so they can get involved and achieve change themselves.

**Comment by rohit-satya** [comment]
@rohanKanojia Please assign this issue to me
