### ISSUE TITLE
Test case in ExternalCommandTest failing on MacOS

### ISSUE THREAD

**Issue by arman-yekkehkhani** [eclipse-jkube/jkube#3006]
### Describe the bug

When running test `execute_whenCommandFailed_thenThrowException` in class `ExternalCommandTest` on MacOS, it fails. It does not happen on Ubuntu. The reason for that is the inconsistent behaviour of command `ls` in the occasion of failure on these operating systems.

If we try to run `ls` in GNU with a nonexistent file as an argument, it fails with exit code 2:
```
$ ls idonotexist || echo $?
ls: cannot access 'idonotexist': No such file or directory
2
```
While on MacOS, the exit code is 1:
```
$ ls idonotexist || echo $?
ls: idonotexist: No such file or directory
1
```

### Eclipse JKube version

SNAPSHOT

### Component

JKube Kit

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. Use MacOS
2. Run tests inside class `ExternalCommandTest`
3.  Test case `execute_whenCommandFailed_thenThrowException` will fail

### Expected behavior

Either the test case should be platform-independent or disabled on MacOS (like Windows)

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3

### Environment

macOS

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Should it be disabled on MacOS as well as Windows?

**Comment by rohanKanojia** [comment]
@arman-yekkehkhani : Okay, let's disable it on MacOS. Also, I would add an equivalent test for MacOS  (`@EnabledOnOs(OS.MAC)`) as well that verifies behavior on MacOS.

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Thx! Could you assign it to me? I can make a PR for that.

**Comment by manusa** [comment]
Maybe we can just check that the exit code is not 0 which will work in both OSs

**Comment by manusa** [comment]
Or just modify the command for something that's cross-os (*nix/bsd) compatible.
