### ISSUE TITLE
SerializationTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3027]
### Component

None

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/91be299e4b103ddf8db2029830dfa44176b62df2/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java#L84-L85

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. Once we use it, we can omit `isInstanceOf(Pod.class)` from line 85

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in SerializationTest
- [ ] `isInstanceOf(Pod.class)` is removed

**Comment by jasonmokk** [comment]
Hi @rohanKanojia I'd like to work on this as my first contribution. Could you please assign this to me?

**Comment by jasonmokk** [comment]
@rohanKanojia My apologies, thank you for informing me about the process. I will look into the [first-timers-only](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) issues
