### ISSUE TITLE
OCIRegistryClient : Replace deprecated `org.apache.commons.io.input.CountingInputStream` with `org.apache.commons.io.input.BoundedInputStream`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3029]
### Component

JKube Kit

### Description

We're using CountingInputStream for pushing helm charts to OCI registries:

https://github.com/eclipse-jkube/jkube/blob/7d08fb086e056e60a7b5ac4533d4bc3a2bdcf09f/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIManifestLayer.java#L37

In recent releases of Apache commons io, this class has been marked as `@Deprecated` (see [javadoc](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CountingInputStream.html)). We should replace this with the suggested alternative.

After making changes, we also need to verify that the functionality is also working as expected. For that you'll need to generate a helm chart and push it to some OCI registry (DockerHub, Quay, GitHub Container Registry etc). You can watch this demo video to get idea of workflow : :tv: [Sprint 244 - Eclipse JKube: Helm push to OCI repository](https://youtu.be/0R-ERhXiUTA)

### Expected Behavior
`CountingInputStream` is replaced with suggested alternative in [JavaDoc](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CountingInputStream.html)

### Acceptance Criteria
- [ ] `CountingInputStream` is replaced with `BoundedInputStream`
- [ ] Project compiles cleanly after making changes
- [ ] Helm Chart Push functionality is working after making changes

**Comment by rohit-satya** [comment]
@rohanKanojia Please assign this to me

**Comment by Thulasithang** [comment]
Hey @rohanKanojia I would like to try this out. Could you please assign this to me?

**Comment by Thulasithang** [comment]
Hey @rohanKanojia. With the changes made, the helm-chart is pushed to the OCI repository and I can view the repository in quay.io. But I do get the status 'ImagePullBackOff' when I try 
`kubectl get pods`

I'm assuming that's caused because of some issues in my docker and wsl setup. Or could this issue be related to my changes?
