### ISSUE TITLE
KubernetesClientUtil : Refactor loop to get rid of nested `if` statements

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3030]
### Component

JKube Kit

### Description

This loop in KubernetesClientUtil seems to have a lot of nested statements:

https://github.com/eclipse-jkube/jkube/blob/7d08fb086e056e60a7b5ac4533d4bc3a2bdcf09f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java#L141-L148

We should refactor it. I think we can make use of [Java Stream API](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html) here to get the desired result quite easily.

### Expected Behavior
Nested if statements are removed from for loop 

### Acceptance Criteria
- [ ] Nested if statements are removed from for loop
- [ ] Project compiles cleanly after running `mvn clean install`

**Comment by l3002** [comment]
Hi @rohanKanojia : I can work on this. Could you please assign this issue to me?

**Comment by rohanKanojia** [comment]
@l3002: You already have 2 issues assigned to you at the moment. It's generally advised to not work on multiple things at a time. Will you be okay with picking up this one as well (considering your existing work priorities) ?

**Comment by rohit-satya** [comment]
@rohanKanojia Please assign this to me

**Comment by rohanKanojia** [comment]
@rohit-satya : You've commented on multiple issues. Which one should I assign?

**Comment by l3002** [comment]
@rohanKanojia : I'll be delivering the a PR for #2665 today, so I'm sure I'll be able to work on this issue as well. For #2841, I will try to close this one by this week only. Therefore, If multiple issue assignation complies with the existing policy for this repo, then I'll be glad to work on this.

**Comment by manusa** [comment]
Note that we create new issues every week.

**Comment by rohit-satya** [comment]
> @rohit-satya : You've commented on multiple issues. Which one should I assign?

@rohanKanojia In such a case please assign any one and you can reject me for others if you think I won't be able to deliver in time
