### ISSUE TITLE
HelmLintMojoTest.setUp The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3053]
### Description

The method [HelmLintMojoTest.setUp](https://github.com/eclipse-jkube/jkube/blob/b54dddcbbe8f1083e428f0f65835a1d5441b2df4/kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojoTest.java#L43) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/b54dddcbbe8f1083e428f0f65835a1d5441b2df4/kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojoTest.java#L43

- [x] should be changed to:
```java
  void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by kiratkumar47** [comment]
Hi @manusa ,
Could you please assign this to me.

**Comment by manusa** [comment]
@kiratkumar47  [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22). Or maybe create some new issue if you find something that should be fixed.

**Comment by vijaybhagwat24** [comment]
could you please assign this to me

**Comment by rohanKanojia** [comment]
@vijaybhagwat24 https://github.com/eclipse-jkube/jkube/issues/3053#issuecomment-2126706076

**Comment by vijaybhagwat24** [comment]
I will work on this, kindly assign this to me

**Comment by rohanKanojia** [comment]
@vijaybhagwat24 : This issue is created for new comers, you need to pick some issue that not tagged with `first-timers-only`

**Comment by Sadique982** [comment]
Can I work on this?, i am a newcomer.

**Comment by Sadique982** [comment]
@rohanKanojia I raised a PR
