### ISSUE TITLE
SpringBootGeneratorIntegrationTest :  Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3058]
### Component

JKube Kit

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:
https://github.com/eclipse-jkube/jkube/blob/bfbf08d3e506b94f4e724e96e9ddcb230504b0ee/jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java#L219-L224
users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 
### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by Josephvictor** [comment]
Can I work on this?

**Comment by rohanKanojia** [comment]
@Josephvictor Hello, `help wanted` issues are created for contributors who have already contributed to the project. I can see that you haven’t contributed to the project before.

Even if you are quite skilled, please consider doing one little ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issue to get used to the process. After that, you are invited to move on up to the more difficult tasks, leaving some of the easy tasks to others so they can get involved and achieve change themselves.  

Maybe you should start with issues created for first timers [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only)

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hello, could you assign it to me?
