### ISSUE TITLE
Implement tests for JKubeConfiguration initialization in Mojos (and Tasks)

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3068]
This test should be changed because it's testing multiple things at once.
I didn't want to spend more time on this yet because it's out of the scope of the current changes.
Basically, none of these assertions belong here, since what they are checking is that the Mojo performs the correct JKubeConfiguration initialization, which has nothing to do with "shouldUpload".
We need a (multiple) test(s) here and in other mojos that verify(ies) `shouldSetPushRegistry in JKubeConfiguration` and `shouldSetPullRegistry in JKubeConfiguration`.

_Originally posted by @manusa in https://github.com/eclipse-jkube/jkube/pull/3067#discussion_r1604427751_

**Comment by arman-yekkehkhani** [comment]
@manusa Hi! Is this issue ready for the community members to pick up? If so, I'm interested in working on it.

**Comment by manusa** [comment]
This one is easy enough to get picked up by anyone, however, I'm not sure if the description is clear enough.

The idea is that the Mojo tests include a few cases to ensure that the configuration provided is propagated to the initialized JKubeConfiguration object.

**Comment by clarenced** [comment]
Hi @manusa , I can work on this issue

**Comment by arman-yekkehkhani** [comment]
I have spent some time investigating the code and writing some tests :)

**Comment by rohanKanojia** [comment]
@clarenced : Would it be okay if I find some other issue for you.

**Comment by clarenced** [comment]
Yes no problem :)

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia yeah currently working on it
