### ISSUE TITLE
WatchMojo Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3100]
### Description

The class [WatchMojo](https://github.com/eclipse-jkube/jkube/blob/4cccc93af16fc7dbceee99c385fece3691bc7f56/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java#L17) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/4cccc93af16fc7dbceee99c385fece3691bc7f56/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java#L17

- [ ] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Thulasithang** [comment]
Hey @manusa I'm a first time contributor. I would like to take up this issue. Please consider assigning it to me

**Comment by Thulasithang** [comment]
@rohanKanojia, the "eclipse-jkube/dependencies" check for my PR has failed. I am not sure how to proceed from here. Could I get some guidance on what my next steps should be?

Thank you.

**Comment by rohanKanojia** [comment]
That could probably be a flaky failure. Could you please try force pushing your chages again?
