### ISSUE TITLE
JavaExecGeneratorTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3106]
### Component

JKube Kit

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/94f2303221a4b85bde16a29874cb1803e3e61dcc/jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java#L114-L117

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by bhiwagade-rahul** [comment]
@rohanKanojia can you plz assign this to me
