### ISSUE TITLE
DaemonSetHandlerTest : Convert member field to a local variable 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3108]
### Component

JKube Kit

### Description
DaemonSetHandlerTest is using this member variable that doesn't seem to be getting used outside the set up method:

https://github.com/eclipse-jkube/jkube/blob/94f2303221a4b85bde16a29874cb1803e3e61dcc/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java#L40

We should move it inside `@BeforeEach` method. Also, it would be better if we create a new object rather than relying on mockito.

There is also a deprecated method `asList()` being used 
https://github.com/eclipse-jkube/jkube/blob/94f2303221a4b85bde16a29874cb1803e3e61dcc/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java#L103

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
Redundant member level field `probeHandler` is converted to a local variable and `asList()` is replaced with updated AssertJ method

### Acceptance Criteria
- [ ] Redundant member level field is converted into a local variable
- [ ] An actual instance of ProbeHandler is created instead of a mocked one
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by bhiwagade-rahul** [comment]
@rohanKanojia I want to work on the issue, can you please assign this to me?
