### ISSUE TITLE
HelmServiceTest is failing on windows

### ISSUE THREAD

**Issue by Sintivrousai** [eclipse-jkube/jkube#3116]
Part of #1338 

HelmServiceTest is failing on windows.

[ERROR] Failures:
[ERROR]   HelmServiceTest.generateHelmCharts_whenInvoked_thenGeneratedValuesYamlInAlphabeticalOrder:242
expected:

I can wark on the issue.

**Comment by rohanKanojia** [comment]
I haven't tested it myself but maybe this issue can be fixed by replacing `\n` in string literal with using `String.format` with  `%n` placeholder

**Comment by Sintivrousai** [comment]
Well, I think HelmServiceTest is okey but the HelmServiceDependencyUpdateIT is failing now. Should i open a new issue and do a separate pull request or make a pull request for both

**Comment by rohanKanojia** [comment]
@Sintivrousai : I think it's better to fix it separately in a separate issue
