### ISSUE TITLE
Gradle integration test fails: Failed to create JAR file (jackson-core-2.17.1.jar)

### ISSUE THREAD

**Issue by Josephvictor** [eclipse-jkube/jkube#3125]
### Describe the bug

I'm encountering a failure during my Gradle integration tests. There are a total of 216 tests and all the tests fail. The build fails with the following error message:

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type BuildLifecycleController using ServicesProvider.createBuildLifecycleController().
   > Could not create service of type BuildModelController using VintageBuildControllerProvider.createBuildModelController().
      > Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
         > Could not create service of type ClientInjectedClasspathPluginResolver using BuildScopeServices.createInjectedClassPathPluginResolver().
            > java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /tmp/.gradle-test-kit/caches/jars-9/f1c2d191ae6c7c5a0d5569412fb3bada/jackson-core-2.17.1.jar.

### Actual Behavior
The build fails with errors indicating issues with creating a Jar file.

### Eclipse JKube version

SNAPSHOT

### Component

JKube Kit

### Apache Maven version

other (please specify in additional context)

### Gradle version

other (please specify in additional context)

### Steps to reproduce

1. Clone the repository.
2. Navigate to the `jkube/gradle-plugin/it/src/it/` directory or jkube directory
3. Run mvn clean install
4. Observe the build failure errors.

### Expected behavior

The build should be completed successfully without errors.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Environment
- **OS**: Linux
- **JDK**: 17
- **Maven Version**: 3.9.5
- **Gradle Version**: 8.8
- **JKube Version**: 1.17-SNAPSHOT

**Comment by rohanKanojia** [comment]
I'm able to reproduce this issue on my machine. 

However, I'm not sure why it's passing on CI (see job [PR-3123](https://ci.eclipse.org/jkube/job/Build/job/Sonar/job/PR-3123/2/consoleFull))
