### ISSUE TITLE
Gradle: Ensure Gradle configuration Cache

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3126]
## Description

Mirror of https://github.com/fabric8io/kubernetes-client/pull/6038

> In order to support Gradle's configuration cache, having the Project object in extensions/tasks is not allowed https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:disallowed_types. We can avoid that by injecting the ProjectLayout object directly which is legal.

>> There are a number of types that task instances must not reference from their fields. 
>> These types fall into some categories as follows:
>> - Live JVM state types
>> - Gradle model types
>> - Dependency management types
>>
>> In all cases the reason these types are disallowed is that their state cannot easily be stored or recreated by the configuration cache.

> Specifically
>> Gradle model types (e.g. Gradle, Settings, Project, SourceSet, Configuration etc…​) are usually used to carry some task input that should be explicitly and precisely declared instead.

_@Sineaggi_

**Comment by manusa** [comment]
Issue can be checked with command `./gradlew --configuration-cache clean build k8sBuild` in the `quickstarts/gradle/spring-boot`

```
* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:k8sBuild` of type `org.eclipse.jkube.gradle.plugin.task.KubernetesBuildTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.7/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

Due to the complexity of the operations performed at `GradleUtil.convertGradleProject` and the requirement for multiple project entries (maybe some only available at runtime), it's going to be almost impossible to fix this issue.

I'd suggest to close as won't fix.
I'd only invest more time on this in case this feature becomes critical for some user.

**Comment by rohanKanojia** [comment]
I think we can close this one for now.
