### ISSUE TITLE
AssemblyConfigurationTest :  Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3134]
### Component

JKube Kit

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/AssemblyConfigurationTest.java#L129

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hi, Can I work on this one?
