### ISSUE TITLE
JibServiceTest : Statement lambda can be replaced with expression lambda 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3135]
### Component

JKube Kit

### Description
In the test assertions, we're using statement lambda (with curly braces). Since it's only a single statement, we can simply replace it using expression lambda

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java#L125-L128

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java#L146-L148

### Expected Behavior
Statement lambda can be replaced with expression lambda (Note, that the curly braces and the semicolon need to be removed.)

### Acceptance Criteria
- [ ] Statement lambda can be replaced with expression lambda  in both places in test

**Comment by skayikci** [comment]
Hello @rohanKanojia , could you assign the ticket to me? Thank you.
