### ISSUE TITLE
PortForwardService : Remove duplicated method `getNewestPod`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3136]
### Component

JKube Kit

### Description

We have a method in PortForwardService to find the latest Pod in given list of Pods: 

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java#L208-L218

But this method is already present in the utility class KubernetesHelper 
https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java#L570-L589

We should delete the duplicated method in PortForwardService and use the one defined in KubernetesHelper
### Expected Behavior

Duplicated `getNewestPod` method is removed from PortForwardService and `KubernetesHelper.getNewestPod` is used instead

### Acceptance Criteria
- [ ] Duplicated `getNewestPod` method is removed from PortForwardService
- [ ] `KubernetesHelper.getNewestPod` is used in place of deleted method
- [ ] project should compile cleanly after running `mvn clean install`

**Comment by Flowers2Algernon** [comment]
I want do this, please assign it to me.

**Comment by Flowers2Algernon** [comment]
@rohanKanojia  Of course, sorry I don't carefully read the rule, I will start with first-timers-only issue. 

Thank you for your kind remind.

**Comment by rohanKanojia** [comment]
@Flowers2Algernon : Thanks, you can pick up this issue. But I'd advise you to complete one `first-timers-only` issue.

**Comment by Josephvictor** [comment]
Can I work on this?
