### ISSUE TITLE
ResourceMojoTest is failing on windows

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3139]
### Component

Kubernetes Maven Plugin

### Description

Related to #1338 

ResourceMojoTest is failing on windows due to use of Linux line feed `\n` as line separators in test expectations

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoTest.java#L104

https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoTest.java#L119

This can easily be fixed by wrapping string literal within `String.format(...)` and replacing `\n` with platform independent `%n`. 

### Expected Behavior
ResourceMojoTest is passing on Windows

### Acceptance Criteria
- [x] ResourceMojoTest should pass on Windows after making changes

**Comment by harsha-mangena** [comment]
Hey @rohanKanojia, Can I pick up this issue?

**Comment by rohanKanojia** [comment]
@harsha-mangena  : Hello, `help wanted` issues are created for contributors who have already contributed to the project. I can see that you haven’t contributed to the project before.

Even if you are quite skilled, please consider doing one little ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issue to get used to the process. After that, you are invited to move on up to the more difficult tasks, leaving some of the easy tasks to others so they can get involved and achieve change themselves.  

Maybe you should start with issues created for first timers [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) , then after completing that you can pick up this one?

**Comment by harsha-mangena** [comment]
@rohanKanojia , Sure, will pick small ones at first, thanks for letting me know.

**Comment by Jeevananthammoorthy** [comment]
@rohanKanojia  Could you assign this issue on my name.

**Comment by Jeevananthammoorthy** [comment]
@rohanKanojia  Kindly find the PR https://github.com/eclipse-jkube/jkube/pull/3152
