### ISSUE TITLE
IngressConfigTest :  Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3157]
### Component

JKube Kit

### Description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/d25c6769d1f7b7426d84499238e1fd08623f46bc/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/IngressConfigTest.java#L39

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

Also, we can replace the deprecated ObjectMapper.configure method with whatever is advised in it's [javadoc](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/index.html)

https://github.com/eclipse-jkube/jkube/blob/d25c6769d1f7b7426d84499238e1fd08623f46bc/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/IngressConfigTest.java#L32-L32

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hi, I can work on this. Could you please assign it to me?
