### ISSUE TITLE
[OpenShift Maven Plugin] : Move duplicated methods in Mojos to a common interface

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3160]
### Component

OpenShift Maven Plugin

### Description

When I check all [Mojo classes in openshift-maven-plugin](https://github.com/eclipse-jkube/jkube/blob/master/openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/) module, I see this method duplicated in every Mojo class:

https://github.com/eclipse-jkube/jkube/blob/d25c6769d1f7b7426d84499238e1fd08623f46bc/openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java#L105

We should create an interface OpenShiftJKubeMojo that will contain default implementation for this method. We are already doing a similar thing in `gradle-plugin/` module with [OpenShiftJKubeTask](https://github.com/eclipse-jkube/jkube/blob/master/gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftJKubeTask.java) , all gradle actions are implementing this interface

https://github.com/eclipse-jkube/jkube/blob/d25c6769d1f7b7426d84499238e1fd08623f46bc/gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTask.java#L20

### Expected Behavior
The duplicated method is removed from all OpenShift Maven Plugin *Mojo classes and moved to OpenShiftJKubeMojo interface. All OpenShift Maven Plugin *Mojo classes implement this new interface

### Acceptance Criteria
- [ ] Duplicated method `getLogPrefix()` is removed from all OpenShift Maven Plugin Mojos
- [ ] all OpenShift Maven Plugin Mojos implement this newly added interface

**Comment by lukez963** [comment]
Hi, could I be assigned this issue?

**Comment by lukez963** [comment]
Hi. I'm unsure if creating a OpenShiftJKubeMojo interface would work here. The interface OpenShiftJKubeTask is overriding the getLogPrefix() default implementation from the KubernetesJKubeTask interface. 
However, all OpenShift Maven Plugin Mojo classes inherit their getLogPrefix() implementation from abstract classes (either AbstractJKubeMojo or AbstractDockerMojo) - if the overriding getLogPrefix() is removed from each Mojo class and moved to the OpenShiftJKubeMojo interface, I believe the classes will preferentially call the getLogPrefix() implementation from AbstractJKubeMojo or AbstractDockerMojo instead. 
The simplest solution to this I see is to move the getLogPrefix() implementation from AbstractJKubeMojo and AbstractDockerMojo to the interface KitLoggerProvider, which they both implement (I believe the proposed interface OpenShiftJKubeMojo would successfully override getLogPrefix then). But this wouldn't work if KitLoggerProvider is meant to be a functional interface or for other reasons I don't see.

**Comment by vijaybhagwat24** [comment]
Hi @rohanKanojia ,
is this issue open? If yes, kindly see my analysis below and if it is ok then please assign this to me.

Analysis:

1. I agree to @lukez963 analysis. The getLogPrefix() should be added to KitLoggerProvider(Interface) if it is not meant to be functional interface and it is super class of AbstractDockerMojo and AbstractJKubeMojo.
2. Also I could see usage of "getLogPrefix()" only in AbstractDockerMojo and AbstractJKubeMojo classes.

Action Items:
1. Remore occurrences of getLogPrefix() from all mojo implementations and add default method to KitLoggerProvider and modify abstract classes accordingly.

If anything is missing and needs to be taken into consideration, kindly add.

**Comment by rohanKanojia** [comment]
@vijaybhagwat24 : Sorry I missed the fact that Maven plugins are affected by this issue https://github.com/eclipse-jkube/jkube/issues/147. They don't have a common parent class like in the case of gradle plugins.

> Remore occurrences of getLogPrefix() from all mojo implementations and add default method to KitLoggerProvider and modify abstract classes accordingly.

Moving the method to KitLoggerProvider will reduce duplication in kubernetes maven plugin classes. But I really wanted to somehow get rid of methods in OpenShift classes. Not sure whether to close this issue or to make changes.

**Comment by rohanKanojia** [comment]
@vijaybhagwat24 : I was wrong in my initial assumption that this issue is affected by #147 . In Gradle Plugins, getLogPrefix() gets reused with the help of interfaces rather than classes.

We can still refactor openshift maven plugins Mojos by creating a new interface that will extend KitLoggerProvider interface and make all OpenShift**Mojos extend this interface.

However, I'm not sure we should do it  now. This is a slightly involved task, it's not suitable for new comers at the moment. Maybe in future it can become slightly easier after we restructure the project.
