### ISSUE TITLE
JavaExecGenerator does not honor %t setting 

### ISSUE THREAD

**Issue by ecausarano** [eclipse-jkube/jkube#3161]
### Describe the bug

When setting the image name to `%t` in order to create a different tag when pushing to the container registy, the JavaExecGenerator will add its own `latest` tag regardless.

This breaks tagging to immutable repositories, where `latest` tags make no sense and will cause the push to fail.

### Eclipse JKube version

1.16.2

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

Choose `%t` in the image name configuration
Configure the target repository to be immutable (eg. AWS ECR) 
Try to push

### Expected behavior

The plugin should only attempt to add the timestamped tag, no `latest` tags added.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Amazon

**Comment by rohanKanojia** [comment]
@ecausarano : Is it possible to share a reproducer project? I tried reproducing this but could not reproduce the issue. Here are the steps I followed:

1. Clone https://github.com/rohankanojia/podsetoperatorinjava
2. Change `jkube.generator.name` property in[ `pom.xml`](https://github.com/rohanKanojia/podsetoperatorinjava/blob/master/pom.xml#L24) to `quay.io/${image.user}/${project.artifactId}:%t`
3. Run `mvn k8s:build`

I was able to see image being tagged with timestamp:

```
[INFO] k8s: [quay.io/rohankanojia/podset-operator-in-java:snapshot-240613-102153-0649] "java-exec": Created docker-build.tar in 65 milliseconds
[INFO] k8s: [quay.io/rohankanojia/podset-operator-in-java:snapshot-240613-102153-0649] "java-exec": Built image sha256:4d492
[INFO] k8s: [quay.io/rohankanojia/podset-operator-in-java:snapshot-240613-102153-0649] "java-exec": Tag with latest
```

**Comment by rohanKanojia** [comment]
okay, I think I now understand the problem now. Image is correctly tagged with timestamp, however JKube is adding an additional `<tag>` in Build configuration. This results in an extra image getting created: 

```
REPOSITORY                                     TAG                           IMAGE ID       CREATED              SIZE
quay.io/rohankanojia/podset-operator-in-java   latest                        dd581f0fe6ef   About a minute ago   507MB
quay.io/rohankanojia/podset-operator-in-java   snapshot-240613-102851-0116   dd581f0fe6ef   About a minute ago   507MB
```

This `latest` tag is being added for projects that have versions containing `SNAPSHOT`

https://github.com/eclipse-jkube/jkube/blob/cb683ea612f46c07c39c38345e1587ec7b708fe2/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L237-L240


Adding a check here to not add `latest` tag when image name contains `%t` fixes the issue
```diff
-        if (getProject().getVersion().endsWith("-SNAPSHOT")) {
+        if (getProject().getVersion().endsWith("-SNAPSHOT") && !getImageName().contains("%t")) {
```

**Comment by ecausarano** [comment]
That would fix it, but the tag name is already processed in another part of the codebase. ([ImageNameFormatter.java](https://github.com/eclipse-jkube/jkube/blob/6c7f976af489fd86aa89138c94782b9d1e8b3ea5/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/ImageNameFormatter.java#L186)

I'm no Docker guru, is there a reason for explicitly adding the `latest` tag? Wouldn't the Registry automatically add it?

**Comment by rohanKanojia** [comment]
I'm checking history of this change and it seems to have been introduced in https://github.com/fabric8io/fabric8-maven-plugin/pull/186 . It doesn't provide much insight on why this was added.
