### ISSUE TITLE
BuildService : Replace outdated method for joining strings with inbuilt `String.join`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3179]
### Component

JKube Kit

### Description

In BuildService, we're using a utility method from EnvUtil to join a sequence of characters with a delimiter string:

https://github.com/eclipse-jkube/jkube/blob/8b3ddfae846d2b8f485b97b8dc199227ded3fddc/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java#L80

Looks like this method was written before Java 8. Java 8 provides [String.join](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.Iterable-) that can achieve same task.

### Expected Behavior
We should remove this method EnvUtil.stringJoin and use `String.join` instead.

### Acceptance Criteria
- [x] Remove `EnvUtil.stringJoin` and it's corresponding unit test
- [x] Repace usage of `EnvUtil.stringJoin` with `String.join`

**Comment by rohanKanojia** [comment]
@llTheBlankll : It's better to rely on method provided by JDK as it would be better tested and more reliable.

**Comment by llTheBlankll** [comment]
I don't think 
`log.info(String.join(buildConfig.getDockerArchive(), ": Loaded tarball in ", EnvUtil.formatDurationTill(time)));`
is pleasing to the eye compared to
`log.info("%s: Loaded tarball in %s", buildConfig.getDockerArchive(), EnvUtil.formatDurationTill(time));`

or

`log.warn(String.join(imageConfig.getDescription(), ": ", exp.getMessage(), " (old image)", (exp.getCause() != null ? " [" + exp.getCause().getMessage() + "]" : "")));`

compared to

`log.warn("%s: %s (old image)%s", imageConfig.getDescription(), exp.getMessage(), (exp.getCause() != null ? " [" + exp.getCause().getMessage() + "]" : ""));`
Although String.join is tested and reliable. In my opinion, leaving it as is better for code readability.

**Comment by rohanKanojia** [comment]
@llTheBlankll : Maybe I didn't explain the issue properly. I'm only referring to replacing `EnvUtil.stringJoin(tags, ",")` with `String.join(",", tags`

**Comment by llTheBlankll** [comment]
Nevermind then, if its EnvUtil.stringJoin I'm with you that String.join should be used.

**Comment by llTheBlankll** [comment]
Also I think buildImage is complex as well... maybe there's a way to reduce the complexity.

**Comment by rohanKanojia** [comment]
@llTheBlankll : Feel free to open a new issue about it.

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hey Rohan, Can I work on this?
