### ISSUE TITLE
Replace deprecated method from Updatable interface

### ISSUE THREAD

**Issue by arman-yekkehkhani** [eclipse-jkube/jkube#3188]
### Component

None

### Description
Method `Updatable.replace` is used in several places in the project. However, the method is deprecated, and Javadoc advises using the method `update` instead. The reason behind it is explained in [alternatives-to-createOrReplace-and-replace](https://github.com/fabric8io/kubernetes-client/blob/main/doc/FAQ.md#alternatives-to-createOrReplace-and-replace).

**Comment by manusa** [comment]
We should start by listing the places where this method is used and then evaluate the strategy to replace it one by one (edit, update, and so on).

**Comment by arman-yekkehkhani** [comment]
@manusa Thanks! I searched through the project and found out that this method was only used in method `updateImageName` of class `DockerImageWatcher`. There were a few test cases in `DockerImageWatcherRestartContainerTest` that used it also.

**Comment by abusk** [comment]
@manusa please assign it to me.
