### ISSUE TITLE
Incompatible descriptor's return type: ProcessorConfig

### ISSUE THREAD

**Issue by CroWzblooD** [eclipse-jkube/jkube#3195]
### Describe the bug

![Screenshot 2024-06-25 165304](https://github.com/eclipse-jkube/jkube/assets/91479132/2046311a-5801-4511-a16a-b78f09cf193b)

Error occur in : Jkube->jkube-kit -> profile -> src -> main -> ProfileUtil.java 
Error
The type of getGeneratorConfig() from the type Profile is ProcessorConfig, this is incompatible with the descriptor's return type: ProcessorConfig,
The type of getEnricherConfig() from the type Profile is ProcessorConfig, this is incompatible with the descriptor's return type: ProcessorConfig,
The type of getWatcherConfig() from the type Profile is ProcessorConfig, this is incompatible with the descriptor's return type: ProcessorConfig,

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. Open : Jkube->jkube-kit -> profile -> src -> main -> ProfileUtil.java 
2. U get the error 

### Expected behavior

solution: This error occurred because the method references (Profile::getGeneratorConfig, Profile::getEnricherConfig, and Profile::getWatcherConfig) were not compatible with the expected return type defined by the ProcessorConfigurationExtractor interface.
1st method: 

![Screenshot 2024-06-25 165729](https://github.com/eclipse-jkube/jkube/assets/91479132/92498eba-ea60-49d4-96bf-e79b90d9013a)

2nd method: 

public static final ProcessorConfigurationExtractor GENERATOR_CONFIG = profile::getGeneratorConfig;
public static final ProcessorConfigurationExtractor ENRICHER_CONFIG = profile::getEnricherConfig;
public static final ProcessorConfigurationExtractor WATCHER_CONFIG = profile::getWatcherConfig;

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Windows

**Comment by rohanKanojia** [comment]
@CroWzblooD : Do you have [lombok](https://projectlombok.org/) support enabled in your IDE?

**Comment by CroWzblooD** [comment]
yes it is!  i just rechecked everything it still show the error in my IDE, does the error is only occur from my side can u let me know..

**Comment by rohanKanojia** [comment]
@CroWzblooD : Project is compiling fine on Jenkins (see [logs](https://ci.eclipse.org/jkube/job/Build/job/Java8/job/master/471/)) . There must be some problem in your project setup.

**Comment by CroWzblooD** [comment]
thankyou for letting me know, ill check and fix it from my side , also ill be careful before creating new issue
