### ISSUE TITLE
BuildService 'nocache.length() == 0' can be replaced with 'nocache.isEmpty()'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3198]
### Description

The call to `String.length` can be replaced with `isEmpty` in [BuildService](https://github.com/eclipse-jkube/jkube/blob/9dee5b047481246be704a0408f71fc917fc0ac6c/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java).

The following line:
https://github.com/eclipse-jkube/jkube/blob/9dee5b047481246be704a0408f71fc917fc0ac6c/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java#L219

should be changed to:

```java
            return nocache.isEmpty() || Boolean.parseBoolean(nocache);
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by Aknummoalr** [comment]
Hey @manusa can you please assign this issue to me.

**Comment by bhavana61** [comment]
Hi @manusa , can I work on it?

**Comment by bhavana61** [comment]
@rohanKanojia i am getting this error while trying to push my changes 
fatal: unable to access 'https://github.com/bhavana61/jkube.git/': The requested URL returned error: 403

**Comment by bhavana61** [comment]
is this already assigned to somebody else?
I see now a commit to it...
@rohanKanojia can you help me assign any otehr first timers issue?

**Comment by rohanKanojia** [comment]
@bhavana61 : Are you a first time contributor? Do you see any open ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issues?

**Comment by bhavana61** [comment]
3369 - i can pickup this one.

**Comment by bhavana61** [comment]
you can unasisgn me from here.
