### ISSUE TITLE
ImageChangeTriggerEnricher 'containerToImageMap.size() != 0' can be replaced with '!containerToImageMap.isEmpty()'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3203]
### Description

The call to `Map.size` can be replaced with `isEmpty` in [ImageChangeTriggerEnricher](https://github.com/eclipse-jkube/jkube/blob/8aea35928d3f3157ffcfbd645001adfe4302bbb8/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java).

The following line:

https://github.com/eclipse-jkube/jkube/blob/8aea35928d3f3157ffcfbd645001adfe4302bbb8/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java#L82

should be changed to:

```java
                if (!containerToImageMap.isEmpty()) {
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by YAKSH22WEBSITEHACKERS** [comment]
HI,
KINDLY ASIGN THIS TO ME

**Comment by OrneyVortex** [comment]
Hello @manusa can you assign this to me if not resolved yet?
I can give it a try

**Comment by manusa** [comment]
Hi @OrneyVortex, let's ask the current assignee first. We usually give 1-2 weeks margin to complete the issue. Note that there are still plenty open and unassigned first-timers-only issues https://github.com/eclipse-jkube/jkube/labels/first-timers-only (especially at the bottom of the list).
Hi @YAKSH22WEBSITEHACKERS, are you working on this?

**Comment by vijaybhagwat24** [comment]
may i pick this up?

**Comment by rohanKanojia** [comment]
@ YAKSH22WEBSITEHACKERS  : Unassigning you from the issue as there hasn't been any update since past 1 month
