### ISSUE TITLE
Remove duplicate dependency from `quickstarts/maven/micronaut4` `pom.xml`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3204]
### Component

None

### Description
Micronaut 4 maven quickstart seems to have same dependency declared twice

https://github.com/eclipse-jkube/jkube/blob/8435d6b22bb1cbcc25c8576c308cc9efb7106363/quickstarts/maven/micronaut4/pom.xml#L55-L59

https://github.com/eclipse-jkube/jkube/blob/8435d6b22bb1cbcc25c8576c308cc9efb7106363/quickstarts/maven/micronaut4/pom.xml#L115-L119

We should remove one of the declarations.

### Expected Behavior
Duplicate declaration is removed 

### Acceptance Criteria
- [x] Duplicate declaration of `io.micronaut.test:micronaut-test-junit5` is removed

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hi, can I work on this?
