### ISSUE TITLE
`KubernetesHelperTest.exportKubernetesClientConfigToFile_worksWithKubernetesMockServer` is failing on windows

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3205]
### Component

JKube Kit

### Description

This test is failing on Windows at this line

https://github.com/eclipse-jkube/jkube/blob/8435d6b22bb1cbcc25c8576c308cc9efb7106363/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java#L491

```
Error:  Failures: 
Error:    KubernetesHelperTest.exportKubernetesClientConfigToFile_worksWithKubernetesMockServer:479 
Multiple Failures (1 failure)
-- failure 1 --
Expecting actual:
  "127.0.0.1:54812"
to match pattern:
  "localhost:\d+"
at KubernetesHelperTest.lambda$exportKubernetesClientConfigToFile_worksWithKubernetesMockServer$5(KubernetesHelperTest.java:485)
```

Maybe we should directly use `mockServer.getHostName()` and `mockServer.getPort()` in assertions instead of relying on a pattern

### Expected Behavior
The abovementioned test should pass on windows

### Acceptance Criteria
- [ ] `KubernetesHelperTest.exportKubernetesClientConfigToFile_worksWithKubernetesMockServer`  passes on windows

**Comment by CroWzblooD** [comment]
i would like to work on it

**Comment by CroWzblooD** [comment]
@Test
    @DisplayName("should work with KubernetesClient config provided by KubernetesMockServer")
    void exportKubernetesClientConfigToFile_worksWithKubernetesMockServer(@TempDir Path temporaryFolder) throws IOException {
        // When
        final Path result = KubernetesMockServerUtil.exportKubernetesClientConfigToFile(mockServer, temporaryFolder.resolve("config"));
        // Then
        final io.fabric8.kubernetes.api.model.Config kc = Serialization
            .unmarshal(result.toFile(), io.fabric8.kubernetes.api.model.Config.class);
        assertThat(kc)
            .hasFieldOrPropertyWithValue("currentContext", "mock-server")
            .satisfies(c -> assertThat(c.getContexts())
                .singleElement(InstanceOfAssertFactories.type(NamedContext.class))
                .hasFieldOrPropertyWithValue("name", "mock-server")
                .hasFieldOrPropertyWithValue("context.namespace", "test")
                .hasFieldOrPropertyWithValue("context.user", "mock-server-user")
                .extracting("context.cluster").asString()
                .isEqualTo(mockServer.getHostName() + ":" + mockServer.getPort()) 
            )
            .satisfies(c -> assertThat(c.getClusters())
                .singleElement(InstanceOfAssertFactories.type(NamedCluster.class))
                .hasFieldOrPropertyWithValue("cluster.insecureSkipTlsVerify", true)
                .extracting("cluster.server", "name")
                .allMatch(s -> s.toString().equals(mockServer.getHostName() + ":" + mockServer.getPort())) 
            )
            .satisfies(c -> assertThat(c.getUsers())
                .singleElement(InstanceOfAssertFactories.type(NamedAuthInfo.class))
                .hasFieldOrPropertyWithValue("name", "mock-server-user"));
    }
    
In this code can u tell me what hostname and port should be passed

**Comment by rohanKanojia** [comment]
@CroWzblooD : Are you still working on this issue?

**Comment by CroWzblooD** [comment]
Im sorry i work on it but got stuck somewhere and forgeted pls assign it to @raushan606
