### ISSUE TITLE
ImageName 'registry.length() > 0' can be replaced with '!registry.isEmpty()'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3230]
### Description

The call to `String.length` can be replaced with `isEmpty` in [ImageName](https://github.com/eclipse-jkube/jkube/blob/0fada55c64b7d1bb018b4497ce0e1468fd13d05f/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java).

The following line:
https://github.com/eclipse-jkube/jkube/blob/0fada55c64b7d1bb018b4497ce0e1468fd13d05f/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L132

should be changed to:

```java
        return registry != null && !registry.isEmpty();
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by AhmedFaizanDev** [comment]
Hey, Can i work on this ?

**Comment by JosueGonzalez046** [comment]
Hello how does this work new to coding and would love to contribute

**Comment by rohanKanojia** [comment]
@JosueGonzalez046 : Please go through our [contributing guide](https://www.eclipse.org/jkube/contributing) to get an idea of how you can start contributing.

**Comment by SamarthKoli** [comment]
Hello can you assign this issue to me
