### ISSUE TITLE
MappingConfig 'filenameTypes.length() > 0' can be replaced with '!filenameTypes.isEmpty()'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3233]
### Description

The call to `List.size` can be replaced with `isEmpty` in [MappingConfig](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java).

The following line:
https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java#L41

should be changed to:

```java
        return kind != null && filenameTypes != null && !filenameTypes.isEmpty();
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by jesslane94** [comment]
Hi, this is my first time contributing to this project! Can this be assigned to me? :] Thank you!

**Comment by AhmedFaizanDev** [comment]
Hey, could i contribute to this project too ?

**Comment by rohanKanojia** [comment]
@AhmedFaizanDev : Yes, but you need to pick up some other issue. This is already assigned to someone else.
