### ISSUE TITLE
OpenShiftBuildServiceUtils 'nocache.length() == 0' can be replaced with 'nocache.isEmpty()'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3235]
### Description

The call to `String.length` can be replaced with `isEmpty` in [OpenShiftBuildServiceUtils](https://github.com/eclipse-jkube/jkube/blob/e612ce5a47f33ef0512e9b518efc3695342ffd5f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java).

The following line:
https://github.com/eclipse-jkube/jkube/blob/e612ce5a47f33ef0512e9b518efc3695342ffd5f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java#L253

should be changed to:

```java
      return nocache.isEmpty() || Boolean.parseBoolean(nocache);
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by Priya-753** [comment]
This is my first time contributing to this project. Can this be assigned to me?

**Comment by AhmedFaizanDev** [comment]
can i work on this project ?

**Comment by rohanKanojia** [comment]
@AhmedFaizanDev : Could you please pick some issue that's not assigned to anyone?
