### ISSUE TITLE
RegistryConfigTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3238]
### Component

JKube Kit

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/b594cb13775dd64d13cbda48314c80f99082ef0f/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/RegistryConfigTest.java#L45
users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by manusa** [comment]
> Do I need to update changes wherever `asList()` is used in the test all over the module or just in `RegistryConfigTest`?

Just in the mentioned class
