### ISSUE TITLE
JibServiceUtilTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3242]
### Component

None

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/b594cb13775dd64d13cbda48314c80f99082ef0f/jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java#L320

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hi! Can I work on this issue?

**Comment by vijaybhagwat24** [comment]
Hi @rohanKanojia,
could you please assign this to me?
thank you.
