### ISSUE TITLE
ImageNameTest: Unnecessary 'toString()' call

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3261]
### Description

The class [ImageNameTest](https://github.com/eclipse-jkube/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java#L148) presents the issue: Unnecessary 'toString()' call.

The following line:
https://github.com/eclipse-jkube/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java#L148
should be changed to:

```java
            "repo:%goodbye", "repo:#hashtagit", "repo:F)xcz(", "repo:-foo", "repo:..","repo:" + longTag,
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by Sumeet-2023** [comment]
Hey, can u assign me these issue?

**Comment by SamarthKoli** [comment]
can i contribute on this page i am new beginner contributor this repo

**Comment by rohanKanojia** [comment]
@SamarthKoli : Sorry, I checked this. This has already been fixed in https://github.com/eclipse-jkube/jkube/pull/3293
