### ISSUE TITLE
PortForwardService : Anonymous `new Thread()` can be replaced with `new Thread(() -> {…}) `

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3285]
### Component

JKube Kit

### Description
This anonymous class can be replaced with `new Thread()` call receiving a lambda: 

https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java#L172-L178

### Expected Behavior
Anonymous class is replaced with lambda

### Acceptance Criteria
- [x] Anonymous class is replaced with lambda in PortForwardService
- [x] PortForwardServiceTest is passing after making this change

**Comment by Er-Sadiq** [comment]
Hi , I would Like to take this as I am working on it I'll soon raise a PR ,Thank you

**Comment by rohanKanojia** [comment]
@Er-Sadiq : Someone else already created a pull request #3292 , however, the contributor hasn't signed the Eclipse Contributor Agreement.

**Comment by Er-Sadiq** [comment]
@rohanKanojia I am really Sorry I didn't notice that it was hidden till now
