### ISSUE TITLE
ImageNameTest : refactor `namesUsedByDockerTests()` test into two separate tests

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3288]
### Component

None

### Description
I see `namesUsedByDockerTests()` and I see several problems with it:
- We are computing a repeating string literal using a for loop. We can simply replace it with [Apache StringUtils.repeat
](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#repeat(java.lang.String,int))
https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java#L140-L160
- This test is testing both valid name and invalid names in same test, we should test these in two separate tests

I think we should split this test into two tests, maybe we can place them in a nested test like this:
```java
    @Nested
    @DisplayName("used by docker")
    class UsedByDockerTests {
        @ParameterizedTest
        @DisplayName("illegal")
        @ValueSource(strings = {""})
        void illegalNames(String name) {
            
        }
        
        @ParameterizedTest
        @DisplayName("legal")
        @ValueSource(strings = {""})
        void legalNames(String name) {
            
        }
    }
```

### Expected Behavior
`namesUsedByDockerTests` is refactored to be better readable

### Acceptance Criteria
- [ ] `ImageNameTest.namesUsedByDockerTests` is refactored to be better readable
- [ ] `ImageNameTest.namesUsedByDockerTests` should pass post refactor

**Comment by arman-yekkehkhani** [comment]
@rohanKanojia Hi can I work on this?
