### ISSUE TITLE
ControllerViaPluginConfigurationEnricherTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3289]
### Component

None

### Task description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricherTest.java#L172

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by aizwal9** [comment]
Hi ,
 
I can work on this. You can assign it to me just need to replace deprecated asList function to asInstanceOf(InstanceOfAssertFactories.list(type.class)) and verify test right?

Thank you!

**Comment by rohanKanojia** [comment]
@aizwal9 : Are you contributing for the first time? 


`help wanted` issues are created for contributors who have already contributed to the project. I can see that you haven’t contributed to the project before.

Even if you are quite skilled, please consider doing one little ([`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) ) issue to get used to the process. After that, you are invited to move on up to the more difficult tasks, leaving some of the easy tasks to others so they can get involved and achieve change themselves.  

Maybe you should start with issues created for first timers [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only)  , then after completing that you can pick up this one?

**Comment by aizwal9** [comment]
Sure @rohanKanojia let me take a look at some of the open issues with first-timers-only tag

**Comment by aizwal9** [comment]
Can you assign #3257 can you assign this one to me

**Comment by rohanKanojia** [comment]
@aizwal9 : done

**Comment by aizwal9** [comment]
Hi @rohanKanojia I have completed #3257 and raised PR can I pick this issue now or have to wait until previous PR merges?

**Comment by rohanKanojia** [comment]
@aizwal9 : Yes, let me assign it to you.
