### ISSUE TITLE
IngressEnricherTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3290]
### Component

JKube Kit

### Task description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java#L119

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by Switchharsh** [comment]
Hi, I would like to work on this issue. This is my first time working on an Opensource issue so I might need some guidance. I will replace all occurrences of `asList()` method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`. 

Thank you!

**Comment by Piotr-Filochowski** [comment]
Hi, can i be assigned to this issue?
Thank you

**Comment by vijaybhagwat24** [comment]
Hi,
if this is not resolved, kindly assign this to me.
thanks

**Comment by rohanKanojia** [comment]
@Piotr-Filochowski : Are you still working on this issue?

**Comment by Piotr-Filochowski** [comment]
Okey, sorry i didn't have time to work on it. I unassigned myself.
