### ISSUE TITLE
HelmService: ''stream().forEach()'' can be replaced with 'forEach()'' (may change semantics)

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3336]
### Description

The class [HelmService](https://github.com/eclipse-jkube/jkube/blob/1d2ca4a6b61d70038f510a0be3e7d6178f0824d3/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L468) presents the issue: ''stream().forEach()'' can be replaced with 'forEach()'' (may change semantics).

The following line:
https://github.com/eclipse-jkube/jkube/blob/1d2ca4a6b61d70038f510a0be3e7d6178f0824d3/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L468
should be changed to:

```java
      inputMap.forEach((key, value) -> result.put(key, sortValuesYamlRecursive(value)));
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by denizOgut** [comment]
Hey, I'm interested in this. Can you assign it to me?
