### ISSUE TITLE
KubernetesHelperTest: Casting 'serverUrls' to 'List<?>' is redundant

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3337]
### Description

The class [KubernetesHelperTest](https://github.com/eclipse-jkube/jkube/blob/7d3b969bac9bb1ffcb04d49af30e6840dd0cefb0/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java#L493) presents the issue: Casting 'serverUrls' to 'List<?>' is redundant.

The following line:
https://github.com/eclipse-jkube/jkube/blob/7d3b969bac9bb1ffcb04d49af30e6840dd0cefb0/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java#L493
should be changed to:

```java
                  List<String> actualUrls = serverUrls.stream()
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by fr35wo** [comment]
Hi, can i take this task?
I want to start my contributions
