### ISSUE TITLE
CleanupModeTest : refactor test to use `@ParameterizedTest` instead of loop

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3345]
### Component

JKube Kit

### Description

We have this test that's building an array of input/output values and then iterating over them to test each entry:

https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/CleanupModeTest.java#L31-L45

We can easily refactor this test to use JUnit's  [`@ParameterizedTest`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) , this would make it more readable.

### Expected Behavior

`parse()` test is refactored to use parameterized tests

### Acceptance Criteria
- [ ] `for` loop is replaced with a Parameterized test
- [ ] CleanupModeTest is still passing after refactor

**Comment by rohanKanojia** [comment]
@raushan606 : Sorry, it looks like @Harsh4902  already created a PR to fix the issue. Could you please find some other issue to work on?

**Comment by Harsh4902** [comment]
@rohanKanojia Sorry for the mistake. Can you please assign it to me?
