### ISSUE TITLE
BaseEnricherTest : Use class level `@Getter` annotation in `BaseEnricher.TestEnricher` nested class

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3364]
### Component

JKube Kit

### Description
BaseEnricherTest is creating as a nested dummy enricher  class for testing

https://github.com/eclipse-jkube/jkube/blob/c2c9a0cdd076fbeb25087a6598b448b5271d6293/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/BaseEnricherTest.java#L50-L56

There are only two fields in this class, both annotated with[`@Getter`](https://projectlombok.org/features/GetterSetter) , if all class members need to have [`@Getter`](https://projectlombok.org/features/GetterSetter) 
annotation, we can move the annotation to class level.

### Expected Behavior
[`@Getter`](https://projectlombok.org/features/GetterSetter) annotation is moved from field level to class level

### Acceptance Criteria
- [x] [`@Getter`](https://projectlombok.org/features/GetterSetter)  is removed from fields and added on top of class declaration
- [x] BaseEnricherTest is passing after making these changes

**Comment by fr35wo** [comment]
Hi, can i take this task?
I want to start my contributions

**Comment by vijaybhagwat24** [comment]
kindly assign this to me.
