### ISSUE TITLE
ValidationUtil: Empty string in concatenation

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3367]
### Description

The class [ValidationUtil](https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java#L42) presents the issue: Empty string in concatenation.

The following line:
https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java#L42
should be changed to:

```java
                    leafBean = hasMetadata.getKind() + ": " + metadata;
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by Kishore1K** [comment]
Hi is this issue still open

**Comment by manusa** [comment]
Yes, thx!
