### ISSUE TITLE
GradleUtil: Explicit type argument Configuration can be replaced with <>

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3368]
### Description

The class [GradleUtil](https://github.com/eclipse-jkube/jkube/blob/edd44d90d52a013f33d22cd38f682b59facef53b/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java#L117) presents the issue: Explicit type argument Configuration can be replaced with <>.

The following line:
https://github.com/eclipse-jkube/jkube/blob/edd44d90d52a013f33d22cd38f682b59facef53b/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java#L117
should be changed to:

```java
    return new ArrayList<>(gradleProject.getConfigurations()).stream()
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by pujakarakoti07** [comment]
can I get this issue to fix?

**Comment by shree-crypto** [comment]
can i try this issue as my first timer ?

**Comment by manusa** [comment]
> can i try this issue as my first timer ?

Hi @shree-crypto, you've been assigned #2591

**Comment by Theo64-dev** [comment]
Hi, first timer here, I just signed the ECA and everything, can I be assigned this?
