### ISSUE TITLE
MicronautGenerator: Lambda can be replaced with method reference

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3370]
### Description

The class [MicronautGenerator](https://github.com/eclipse-jkube/jkube/blob/239ef826edd3f894191b728e460877e25d924c08/jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java#L46) presents the issue: Lambda can be replaced with method reference.

The following line:
https://github.com/eclipse-jkube/jkube/blob/e2c44f4d7270e9c3f096deaa02b006f89c215bc6/jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java#L52
should be changed to:

```java
        return nestedGenerator.getEnv(super::getEnv, prePackagePhase);
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by devchh** [comment]
Hey @manusa! Can I be assigned this?

**Comment by manusa** [comment]
> Hey @manusa! Can I be assigned this?

Hi @devchh 

It's been 2 weeks since the issue was assigned, are you still working on it or I can assign to someone else?

**Comment by devchh** [comment]
Hey @manusa !  Hope you're well. Just need to finish the log in stuff. Should be done sometime this week. Sorry for this just caught up.
