### ISSUE TITLE
SpringBootGenerator: Lambda can be replaced with method reference

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3371]
### Description

The class [SpringBootGenerator](https://github.com/eclipse-jkube/jkube/blob/03cfc9119caf9a6dec066f3b2254b7dd185d6933/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java#L87) presents the issue: Lambda can be replaced with method reference.

The following line:
https://github.com/eclipse-jkube/jkube/blob/03cfc9119caf9a6dec066f3b2254b7dd185d6933/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java#L87
should be changed to:

```java
        return nestedGenerator.getEnv(super::getEnv, prePackagePhase);
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by Kishore1K** [comment]
Can I take this issue

**Comment by manusa** [comment]
Hi @Kishore1K, [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

Please check the [contributing guide](https://eclipse.dev/jkube/contributing/#finding-an-issue-to-work-on) for more information.

**Comment by pujakarakoti07** [comment]
Can I resolve this issue?

**Comment by manusa** [comment]
Hi @pujakarakoti07, I have just assigned #3368 to you.

**Comment by Aryant-Tripathi** [comment]
@manusa May I be allowed to work on this issue?
