### ISSUE TITLE
Docker file optimization

### ISSUE THREAD

**Issue by fr35wo** [eclipse-jkube/jkube#3376]
### Component

quickstarts

### Description
Set environment variable and don't use it
Lack of clear working directory setting: Not setting a clear working directory can reduce readability.

https://github.com/eclipse-jkube/jkube/blob/522baa2100fc95ea3ca27a0a6e1a6d43861e7182/quickstarts/maven/plugin/app/Dockerfile#L17

https://github.com/eclipse-jkube/jkube/blob/522baa2100fc95ea3ca27a0a6e1a6d43861e7182/quickstarts/gradle/plugin/app/Dockerfile#L19-L20

I think it would be better to fix it like this

```
FROM quay.io/jkube/jkube-java:0.0.15

ENV JAVA_APP_DIR=/deployments

**Set working directory**
WORKDIR ${JAVA_APP_DIR}

COPY maven/build/libs/*.jar app.jar
COPY maven/build/classes/java/main/jkube-extra/ files/

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
```

Or, it might be a good idea to delete Set working directory.

### Expected Behavior
Setting working directory: By using the WORKDIR command to set the working directory, subsequent commands are now clearer.
Improved readability: The overall structure has been organized to improve readability.

**Comment by fr35wo** [comment]
@rohanKanojia Could I possibly make a PR based on this content?

**Comment by manusa** [comment]
> @rohanKanojia Could I possibly make a PR based on this content?

This seems OK, please do.

**Comment by pujakarakoti07** [comment]
I want to work on this issue.

**Comment by fr35wo** [comment]
I'm going to pr this week

**Comment by fr35wo** [comment]
@rohanKanojia If the variable were only used at build time, it would likely have been set using ARG instead of ENV. Therefore, the environment variable set with the ENV command can be used during the execution of the container, which is why it won't be removed. What do you think?
