### ISSUE TITLE
BuildService: Unused import 'import org.eclipse.jkube.kit.common.RegistryConfig;'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3387]
### Description

The class [BuildService](https://github.com/eclipse-jkube/jkube/blob/f340d005693cfceb0c86e70767bcd6c20309c64f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/BuildService.java#L17) presents the issue: Unused import 'import org.eclipse.jkube.kit.common.RegistryConfig;'.

The following line:
https://github.com/eclipse-jkube/jkube/blob/f340d005693cfceb0c86e70767bcd6c20309c64f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/BuildService.java#L17
should be removed.
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by misim3** [comment]
Hi! I would like to work on this issue. Could I take it on?
