### ISSUE TITLE
DaemonSetHandlerTest: Unused import 'import static org.mockito.Mockito.mock;'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3388]
### Description

The class [DaemonSetHandlerTest](https://github.com/eclipse-jkube/jkube/blob/487021f1a50fbf3a7269286e61dd119e2349c67c/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java#L38) presents the issue: Unused import 'import static org.mockito.Mockito.mock;'.

The following line:
https://github.com/eclipse-jkube/jkube/blob/487021f1a50fbf3a7269286e61dd119e2349c67c/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java#L38
should be removed.
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by gawadeatul** [comment]
Hello @manusa , I am new to the Open Source contribution and really looking forward to contribute in this project. Can I work on this issue?

**Comment by gawadeatul** [comment]
Hello @rohanKanojia,
PR (https://github.com/eclipse-jkube/jkube/pull/3418#issue) is ready, could you please review it and share your feedback.
