### ISSUE TITLE
DebugService: Unused import 'import org.eclipse.jkube.kit.config.image.build.JKubeBuildStrategy;'

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3391]
### Description

The class [DebugService](https://github.com/eclipse-jkube/jkube/blob/f5bfbe963d9d77fc89ddfddcb4a803351430ad35/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java#L32) presents the issue: Unused import 'import org.eclipse.jkube.kit.config.image.build.JKubeBuildStrategy;'.

The following line:
https://github.com/eclipse-jkube/jkube/blob/f5bfbe963d9d77fc89ddfddcb4a803351430ad35/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java#L32
should be removed.
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by ShivamChavan01** [comment]
Hi @manusa,

I apologize for the confusion. This issue had been open for the last two weeks, and since no one was working on it, I thought I’d give it a try. Additionally, my friend was interested in learning how to contribute, so I demonstrated the process to him. He wasn’t familiar with how to create a PR, which is why this happened.

I assure you this won’t happen again, and I appreciate your understanding.

Best regards,
Shivam

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : It's okay, you can close this PR and let your friend create it. Ask him to comment on the issue so that we can assign the issue to him.

**Comment by Vishwas2001** [comment]
can i do it @rohanKanojia ??

**Comment by NavikaAgarwal** [comment]
assign me this, i'll do this "hacktoberfest accepted"

**Comment by rohanKanojia** [comment]
@Vishwas2001 : Hello Are you still working on this issue?

**Comment by shree-crypto** [comment]
would like to do this issue as my first contribution @rohanKanojia

**Comment by manusa** [comment]
Fixed by #3505
