### ISSUE TITLE
ImageStreamServiceTest: Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))                                                                                

### ISSUE THREAD

**Issue by ShivamChavan01** [eclipse-jkube/jkube#3394]
### Component

JKube Kit

### Task description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:
The class [ImageStreamServiceTest](jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java) presents the issue: Usage of the deprecated method asList() from AssertJ.

The following lines of code:
https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java#L248

https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java#L253

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class)) ` instead, we need to update `asList()` calls with this.

### Expected Behavior
AssertJ's` asList() `is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [ ] `asList()` DSL method call is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class)) `in all places

**Comment by ShivamChavan01** [comment]
@rohanKanojia   i dont know how to add labels and please check as im right to issue this task or not

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : Do you want to get this issue assigned to you?

**Comment by ShivamChavan01** [comment]
@rohanKanojia yes

**Comment by SamarthKoli** [comment]
i would like to work on this issue can you assign this to me

**Comment by rohanKanojia** [comment]
@SamarthKoli : This issue is already assigned to someone else. Could you please check for some other open issue?

**Comment by rohanKanojia** [comment]
> yes & one more thing why is the issue number id is https://github.com/eclipse-jkube/jkube/issues/3394 is it okay ??

@ShivamChavan01 : Sorry, I don't understand your question. Could you please elaborate?
