### ISSUE TITLE
 ResourceConfigTest : Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class)) 

### ISSUE THREAD

**Issue by ShivamChavan01** [eclipse-jkube/jkube#3397]
### Component

JKube Kit

### Description
In the latest versions of Assertj asList() DSL method has been marked as deprecated:
The class [ResourceConfigTest](jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java) presents the issue: Usage of the deprecated method asList() from AssertJ.

The following lines of code:
https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java#L154-L155

https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java#L160-L161

https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java#L179-L180

https://github.com/eclipse-jkube/jkube/blob/d2afc38505144ef4d5c1ff084d8e8ab83e9e5637/jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java#L183-L184

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))`  instead, we need to update `asList()` calls with this.

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
 - [ ] asList() DSL method call is replaced with asInstanceOf(InstanceOfAssertFactories.list(type.class)) in all places

**Comment by rohanKanojia** [comment]
> Can I replace this line with

@ShivamChavan01 : I don't think we need to make this change as we're already passing an object of `List` type to `assertThat`

**Comment by ShivamChavan01** [comment]
Okay  what About the Above Changes Can i Make it ??

**Comment by ShivamChavan01** [comment]
> It's a bit strange as I don't see sonar complaining about these occurrences of `asList` . Although refactoring them like you suggested should do no harm.

 Yeah I agree, it's a bit confusing since Sonar didn't flag the asList() occurrences as deprecated for me either.
