### ISSUE TITLE
AbstractHealthCheckEnricher : Use class level `@Getter` annotation in `AbstractHealthCheckEnricher.Config` nested class

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3402]
### Component

JKube Kit

### Description
AbstractHealthCheckEnricher contains a nested class Config

https://github.com/eclipse-jkube/jkube/blob/dad4cc61149c435dbf91a5700a2c7f7cfe7d9a99/jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricher.java#L42-L51

There are only two fields in this class, both annotated with[`@Getter`](https://projectlombok.org/features/GetterSetter) , if all class members need to have [`@Getter`](https://projectlombok.org/features/GetterSetter) 
annotation, we can move the annotation to class level.

### Expected Behavior
[`@Getter`](https://projectlombok.org/features/GetterSetter) annotation is moved from field level to class level

### Acceptance Criteria
- [x] [`@Getter`](https://projectlombok.org/features/GetterSetter)  is removed from fields and added on top of class declaration
- [x] AbstractHealthCheckEnricherTest is passing after making these changes

**Comment by vikasrajputin** [comment]
Hello @rohanKanojia 
Can I pick this up as my next work?

**Comment by vikasrajputin** [comment]
@rohanKanojia - Could you please review the PR, and let me know if there's any thing missing?
