### ISSUE TITLE
WildflyJARHealthCheckEnricherTest : Replace `Mockito.mock` by creating actual object

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3404]
### Component

JKube Kit

### Component

JKube Kit

### Task description

Related to https://github.com/eclipse/jkube/issues/2316

WildflyJARHealthCheckEnricherTest seems to be using mock here : 
https://github.com/eclipse-jkube/jkube/blob/dad4cc61149c435dbf91a5700a2c7f7cfe7d9a99/jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java#L56

This can easily be refactored to use real object using lombok builders:

```java
      project = JavaProject.builder().build();
      context = JKubeEnricherContext.builder()
          .project(project)
          .build();
```
Similarly these `when(` statements can also be replaced with builder calls like this:

https://github.com/eclipse-jkube/jkube/blob/dad4cc61149c435dbf91a5700a2c7f7cfe7d9a99/jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java#L294-L299

```java
        context = context.toBuilder()
          .project(project.toBuilder()
            .dependency(Dependency.builder()
              .groupId("org.wildfly.plugins")
              .artifactId("wildfly-jar-maven-plugin")
              .version(wildflyJarVersion)
              .build())
            .build())
          .build();
```
Usage of `org.mockito.Mockito.mock`  and `org.mockito.Mockito.when` is removed from WildflyJARHealthCheckEnricherTest
### Expected Behavior
Usages of `Mockito.mock` and `Mockito.when` are removed from WildflyJARHealthCheckEnricherTest

### Acceptance Criteria
- [ ] mock statements are replaced via real variables

**Comment by ShivamChavan01** [comment]
can i do it @rohanKanojia
