### ISSUE TITLE
OpenLibertyUtilsTest : Replace `Mockito.mock` by creating actual object

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3407]
### Component

JKube Kit

### Component

JKube Kit

### Component

JKube Kit

### Task description

Related to https://github.com/eclipse/jkube/issues/2316

OpenLibertyUtilsTest seems to be using mock here : 

https://github.com/eclipse-jkube/jkube/blob/dad4cc61149c435dbf91a5700a2c7f7cfe7d9a99/jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/OpenLibertyUtilsTest.java#L39

This can easily be refactored to use real object using lombok builders:

```java
      project = JavaProject.builder().build();
```
Similarly these `when(` statements can also be replaced with builder calls like this:

https://github.com/eclipse-jkube/jkube/blob/dad4cc61149c435dbf91a5700a2c7f7cfe7d9a99/jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/OpenLibertyUtilsTest.java#L40

```java
    javaProject = JavaProject.builder()
      .baseDirectory(temporaryFolder)
      .build();
```
Usage of `org.mockito.Mockito.mock`  and `org.mockito.Mockito.when` is removed from OpenLibertyUtilsTest
### Expected Behavior
Usages of `Mockito.mock` and `Mockito.when` are removed from OpenLibertyUtilsTest

### Acceptance Criteria
- [ ] mock statements are replaced via real variables

**Comment by ShivamChavan01** [comment]
Can i Do it @rohanKanojia
