### ISSUE TITLE
OpenShift v3.10.0 SpringBoot E2E tests pipeline is consistently failing 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3420]
### Component

None

### Description

Our OpenShift 3.10.0 SpringBoot E2E test pipeline has been consistently failing for past few days, here are some pull requests for reference:
- https://github.com/eclipse-jkube/jkube/pull/3408
- https://github.com/eclipse-jkube/jkube/pull/3416
- https://github.com/eclipse-jkube/jkube/pull/3419
- https://github.com/eclipse-jkube/jkube/pull/3409

I'm not sure whether it's specific to some test that's failing or whether it's degraded state of OpenShift cluster that's causing this. 

When running these tests locally, they seem to pass on my machine.

### Expected Behavior
OpenShift 3.10.0 SpringBoot E2E test pipeline should pass

### Acceptance Criteria
- [ ] OpenShift 3.10.0 SpringBoot E2E test pipeline passes consistently, it should not give flaky errors.

**Comment by manusa** [comment]
Is this issue done?

**Comment by rohanKanojia** [comment]
@manusa Yes, I can see OpenShift 3.10 springboot flow passing on pull requests now
