### ISSUE TITLE
Issue: Replace Deprecated asList() Method in OpenShiftBuildServiceTest

### ISSUE THREAD

**Issue by ShivamChavan01** [eclipse-jkube/jkube#3428]
### Component

JKube Kit

### Description
 The `OpenShiftBuildServiceTest` class contains deprecated usage of the `asList`() DSL method from AssertJ. This method has been replaced by `asInstanceOf(InstanceOfAssertFactories.list(type.class)`). To ensure the code stays up-to-date and free from deprecated methods, we need to update all instances where `asList()` is used.

https://github.com/eclipse-jkube/jkube/blob/a1711a055ed30c60a1eaed082ab15198bd6b1706/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java#L184

https://github.com/eclipse-jkube/jkube/blob/a1711a055ed30c60a1eaed082ab15198bd6b1706/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java#L205

### Expected Behavior

- Identify all occurrences of asList() in the `OpenShiftBuildServiceTest` class.

- Replace each occurrence with `asInstanceOf(InstanceOfAssertFactories.list(type.class)).`

### Acceptance Criteria

- All instances of `asList()` are replaced with the recommended method.

- Unit tests should pass without any errors.

**Comment by ShivamChavan01** [comment]
hey @rohanKanojia  i want to do this

**Comment by ShivamChavan01** [comment]
Hey @rohanKanojia ,

I’m currently working on the OpenShiftBuildServiceTest class, where we are replacing asList() in several places. but noticed the usage of mock() and  where we are using Mockito.mock() in several places. 

Should I replace all the Mockito.mock() instances (like JKubeServiceHub, OpenShiftClient, ArchiveService, etc.) with actual implementations? Or should we use partial mocking where necessary?

https://github.com/eclipse-jkube/jkube/blob/a1711a055ed30c60a1eaed082ab15198bd6b1706/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java#L60-L62



https://github.com/eclipse-jkube/jkube/blob/a1711a055ed30c60a1eaed082ab15198bd6b1706/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java#L68

https://github.com/eclipse-jkube/jkube/blob/a1711a055ed30c60a1eaed082ab15198bd6b1706/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java#L90

Like these  i  was working on the asList() replacements 

Looking forward to your guidance!

Thanks,
Shivam

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : You're right, we should be able to replace most of the mocks with builders. In order to add mocks for OpenShiftClient, we would need to use `@EnableKubernetesMockClient` annotation (see [OpenshiftBuildServiceIntegrationTest](https://github.com/eclipse-jkube/jkube/blob/master/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java))

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : Could you please open a new issue about this?
