### ISSUE TITLE
Issue: Replace Deprecated `asList()` Method in `DockerHealthCheckEnricherTest`

### ISSUE THREAD

**Issue by ShivamChavan01** [eclipse-jkube/jkube#3463]
### Component

JKube Kit

## Description
The `DockerHealthCheckEnricherTest` class currently uses the deprecated AssertJ `asList()` method in the following lines:

https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L220
https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L205

These occurrences need to be replaced with `asInstanceOf(InstanceOfAssertFactories.list(...))` to comply with the latest AssertJ standards.

## Expected Behavior
After replacing the `asList()` method with `asInstanceOf(InstanceOfAssertFactories.list(...))`, the unit tests should pass without any regression or failures.

## Acceptance Criteria
- [x] AC1: Replace the deprecated `asList()` method at [Line 220](https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L220) and [Line 205](https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L205) with `asInstanceOf(InstanceOfAssertFactories.list(...))`.

**Comment by ShivamChavan01** [comment]
Hey @rohanKanojia  & @manusa ,I'm currently working on replacing the deprecated `asList()` method in the `DockerHealthCheckEnricherTest`. Specifically, I need to extract the `exec.command` field. 

I want to use `asInstanceOf(InstanceOfAssertFactories.list(...))`, but I'm unsure about the appropriate class type for this field. Could you please let me know what type `exec.command` should be? Is it a `String`, or does it represent another type?

 https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L220

 https://github.com/eclipse-jkube/jkube/blob/82d13bce9d04596e9a78831f7383e5182fca56bc/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L204-L205

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : Here test seems to be asserting [Probe](https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/Probe.java#L46) model type . `exec.command` seems be be a string list see [ExecAction](https://github.com/fabric8io/kubernetes-client/blob/09e0f40519139602a05715c6b939ac988d532c14/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/ExecAction.java#L40)
