### ISSUE TITLE
FileUtil : Remove unnecessary `.toString()` call

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3472]
### Component

JKube Kit

### Description

FileUtil contains unnecessary `.toString()` that can be removed:

https://github.com/eclipse-jkube/jkube/blob/78e8631c9c101e52dc94f14fb97c16383396afc5/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java#L135

https://github.com/eclipse-jkube/jkube/blob/78e8631c9c101e52dc94f14fb97c16383396afc5/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java#L192

We should remove these redundant `.toString()` calls

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by AnkurRanpariya2005** [comment]
assign me

**Comment by AnkurRanpariya2005** [comment]
I am new to open contribtution, may i know, this request is merged or not?
