### ISSUE TITLE
AbstractMicroprofileHealthCheckEnricherTest : Replace `Mockito.mock` by creating actual object

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3523]
### Component

JKube Kit

### Task description

Related to https://github.com/eclipse/jkube/issues/2316

AbstractMicroprofileHealthCheckEnricherTest seems to be using mock here : 

https://github.com/eclipse-jkube/jkube/blob/2221e72fe51862f1043895ac02235f3e28e33e7b/jkube-kit/jkube-kit-microprofile/src/test/java/org/eclipse/jkube/microprofile/enricher/AbstractMicroprofileHealthCheckEnricherTest.java#L68

This can easily be refactored to use real object using lombok builders:

```java
      project = JavaProject.builder()
        // stuff to set in JavaProject 
        .build();
      context = GeneratorContext.builder()
        .project(project)
        .build();
```
Similarly these `when(` statements can also be replaced with builder calls like this:

https://github.com/eclipse-jkube/jkube/blob/2221e72fe51862f1043895ac02235f3e28e33e7b/jkube-kit/jkube-kit-microprofile/src/test/java/org/eclipse/jkube/microprofile/enricher/AbstractMicroprofileHealthCheckEnricherTest.java#L172-L175

```java
javaProject = javaProject.toBuilder()
  .dependencies(Collections.singletonList(Dependency.builder()
        .groupId("org.example")
        .artifactId("microprofile-fooimpl")
        .build()))
  .build();
```
Usage of `org.mockito.Mockito.mock`  and `org.mockito.Mockito.when` is removed from AbstractMicroprofileHealthCheckEnricherTest
### Expected Behavior
Usages of `Mockito.mock` and `Mockito.when` are removed from AbstractMicroprofileHealthCheckEnricherTest

### Acceptance Criteria
- [x] mock statements are replaced via real variables

**Comment by ShivamChavan01** [comment]
assign me @rohanKanojia

**Comment by saurabhmaurya1** [comment]
Hi @ShivamChavan01, 
Are you still working on it? if not, then @rohanKanojia can you please assign this to me

**Comment by ShivamChavan01** [comment]
@saurabhmaurya1 I'm working sorry I was AFK for a while but I'll will be working on this issue at eve

**Comment by abhishektripathi66** [comment]
Assign me @rohanKanojia
