### ISSUE TITLE
Enable JDK 23 compatibility by updating Lombok version

### ISSUE THREAD

**Issue by arman-yekkehkhani** [eclipse-jkube/jkube#3537]
### Component

None

### Is your enhancement related to a problem? Please describe

This enhancement is related to issue #3462, in which project compilation fails upon JDK 23. A new version of Lomobk has been released that fixes this problem(https://github.com/projectlombok/lombok/issues/3722#issuecomment-2477717822).

### Describe the solution you'd like

Update Lombok to v1.18.36

**Comment by abhishektripathi66** [comment]
Hi @arman-yekkehkhani / @manusa ,

Looks like this issue is resolved.
![image](https://github.com/user-attachments/assets/8201ff9b-3c25-4050-b998-3caa1e20bf36)

**Comment by rohanKanojia** [comment]
Fixed by https://github.com/eclipse-jkube/jkube/pull/3561

**Comment by manusa** [comment]
Did you manage to compile with 23?
